import React, { useState, useEffect, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { useMissionStore } from '../../store/missionStore';
import { MISSION_PROFILES } from '../../types/missionProfiles';
import type { AppScreen } from '../../types/mission';

// ── Types for Interactive Section 2 Components ──────────────────
interface ExplodedComponentInfo {
  id: string;
  name: string;
  system: string;
  whatItDoes: string;
  whyRequired: string;
  missionRole: string;
  configOptions: string[];
  techCode: string;
}

const SATELLITE_COMPONENTS: ExplodedComponentInfo[] = [
  {
    id: 'solar_arrays',
    name: 'Deployable UltraFlex Solar Arrays',
    system: 'Electrical Power System (EPS)',
    whatItDoes: 'Converts incident solar radiation into high-voltage direct current (DC) electricity to power all onboard avionics and instruments.',
    whyRequired: 'Spacecraft cannot carry enough internal chemical battery mass for multi-year operations; continuous photovoltaic generation is essential.',
    missionRole: 'Generates up to 4.8 kW during sunlit orbital arcs while trickling charge to lithium-ion reserve cells for eclipse passes.',
    configOptions: ['Triple-Junction GaAs Cells', 'Silicon Flexible Substrate', 'Single-Axis Articulation Tracking', 'Bifacial Solar Harnessing'],
    techCode: 'SUB-EPS-01',
  },
  {
    id: 'optical_payload',
    name: 'Multispectral High-Res Optical Telescope',
    system: 'Primary Mission Payload',
    whatItDoes: 'Captures ground and atmospheric imagery across visible, near-infrared, and thermal spectrum channels at sub-meter ground resolution.',
    whyRequired: 'Fulfills the core scientific objective of Earth-observation and planetary characterization missions.',
    missionRole: 'Executes programmed swath passes over target regions, streaming raw high-bandwidth sensor data into high-speed solid-state recorders.',
    configOptions: ['Panchromatic 0.35m Imager', 'Hyperspectral 120-band Spectrometer', 'Cryocooled Far-Infrared Sensor', 'Synthetic Aperture Radar (SAR)'],
    techCode: 'PLD-OPT-02',
  },
  {
    id: 'hga_antenna',
    name: 'Dual-Reflector High-Gain Gimballed Antenna',
    system: 'RF Communications & Telemetry',
    whatItDoes: 'Transmits gigabits of science telemetry down to ground stations and receives uplinked command files from flight directors.',
    whyRequired: 'Free space path loss requires narrow, focused microwave beams to communicate over thousands to millions of kilometers.',
    missionRole: 'Maintains locked line-of-sight tracking with deep-space ground dishes, sustaining 150 Mbps X/Ka-band data downlinks.',
    configOptions: ['X-Band Steerable Dish (1.2m)', 'Ka-Band Phased Array', 'Optical Laser Comm Terminal (1.2 Gbps)', 'S-Band Omnidirectional Backup'],
    techCode: 'COM-RF-03',
  },
  {
    id: 'adcs_wheels',
    name: 'Precision Reaction Wheels & Star Trackers',
    system: 'Attitude Determination & Control (ADCS)',
    whatItDoes: 'Measures spacecraft spatial orientation against celestial star catalogs and rotates the spacecraft using internal momentum exchange.',
    whyRequired: 'Maintains jitter-free telescope pointing accuracy without expending exhaustible thruster propellant.',
    missionRole: 'Locks payload pointing within 0.002 degrees during science passes and slews between target coordinates in seconds.',
    configOptions: ['4-Wheel Pyramidal Reaction Array', 'Cold-Gas Micro-Thruster Desaturation', 'Dual Autonomous Star Trackers', 'Redundant Fiber-Optic Gyroscopes'],
    techCode: 'ADC-WHL-04',
  },
  {
    id: 'propulsion_biprop',
    name: 'Hypergolic Monomethylhydrazine Bipropellant Engine',
    system: 'Orbital Maneuvering System (OMS)',
    whatItDoes: 'Generates controlled chemical thrust for initial orbit insertion, plane changes, collision avoidance, and eventual retirement deorbiting.',
    whyRequired: 'Counteracts atmospheric drag decay and enables critical trajectory alterations beyond initial launch vehicle release.',
    missionRole: 'Delivers high specific impulse burns to raise orbit, execute debris-avoidance maneuvers, and drive safe graveyard transfer.',
    configOptions: ['450N Bipropellant Apogee Motor', 'Hall-Effect Xenon Ion Thruster', 'Hydrazine Monopropellant RCS Cluster', 'Green Monopropellant ADN'],
    techCode: 'PRP-ENG-05',
  },
  {
    id: 'thermal_radiator',
    name: 'Deployable Optical Solar Reflector Radiator Panels',
    system: 'Active Thermal Control System (TCS)',
    whatItDoes: 'Rejects internal waste heat generated by high-power microprocessors and sensors outward into the cold vacuum of deep space.',
    whyRequired: 'Electronics overheat rapidly in vacuum without convective air cooling; thermal equilibrium must be maintained via radiative balance.',
    missionRole: 'Keeps onboard avionics within a stable +18°C to +25°C envelope even while exterior hulls alternate between -90°C and +120°C.',
    configOptions: ['Embedded Heat-Pipe Louver Panels', 'Silverized Teflon Multi-Layer Insulation (MLI)', 'Pumped Liquid Loop Ammonia Circuit', 'Ceramic Thermal Barrier Tiles'],
    techCode: 'TCS-RAD-06',
  },
];

// ── Feature Matrix for Section 3 ────────────────────────────────
interface FeatureItem {
  id: string;
  code: string;
  title: string;
  subtitle: string;
  description: string;
  targetScreen: AppScreen;
  highlightTag: string;
  metrics: { label: string; val: string }[];
}

const CORE_FEATURES: FeatureItem[] = [
  {
    id: 'explore_missions',
    code: 'FT-01',
    title: 'EXPLORE MISSIONS',
    subtitle: 'Interactive Space Catalog',
    description: 'Explore real and conceptual space missions across Earth orbit, the Moon, Mars, and deep-space Lagrange points with 3D trajectories and orbital telemetry.',
    targetScreen: 'universe',
    highlightTag: '3D VIRTUAL UNIVERSE',
    metrics: [{ label: 'Destinations', val: '6+ Regimes' }, { label: 'Trajectory Fidelity', val: 'Real-time RK4' }],
  },
  {
    id: 'create_mission',
    code: 'FT-02',
    title: 'CREATE MISSION',
    subtitle: 'Custom Mission Architect',
    description: 'Define your own space program from scratch. Select launch sites, set orbital inclinations, allocate payload budgets, and select spacecraft architectures.',
    targetScreen: 'onboarding',
    highlightTag: 'STEP-BY-STEP BUILDER',
    metrics: [{ label: 'Launch Sites', val: '5 Global Spaceports' }, { label: 'Budget Engine', val: 'Real-time Cost Cap' }],
  },
  {
    id: 'demo_mission',
    code: 'FT-03',
    title: 'DEMO MISSION',
    subtitle: 'Instant Pre-Configured Flight',
    description: 'Jump straight into an active flight without setup. Try CartoSat-3D, AstroSat-Next, or Gaganyaan-H1 pre-loaded with live simulated telemetry.',
    targetScreen: 'mission-control',
    highlightTag: 'ZERO-SETUP FLIGHT',
    metrics: [{ label: 'Profiles', val: '4 Ready Missions' }, { label: 'Startup Time', val: '< 1 Second' }],
  },
  {
    id: 'digital_twin',
    code: 'FT-04',
    title: 'SPACE MISSION DIGITAL TWIN',
    subtitle: 'Live Telemetry & Subsystems',
    description: 'Visualize a real-time digital mirror of the spacecraft. Monitor solar flux, internal bus voltages, thermal gradients, and battery depth of discharge.',
    targetScreen: 'digital-twin',
    highlightTag: 'REAL-TIME TWIN',
    metrics: [{ label: 'Subsystems', val: '7 Discrete Busses' }, { label: 'Telemetry Stream', val: '10 Hz Ingest' }],
  },
  {
    id: 'satellite_config',
    code: 'FT-05',
    title: 'SATELLITE CONFIGURATION',
    subtitle: 'Mission-Matched Spacecraft',
    description: 'Choose from 4 specialized satellite classes matched directly to your mission: Earth Observation, Telecom, Deep Space Probe, and Crewed Capsule.',
    targetScreen: 'satellite',
    highlightTag: 'INTELLIGENT MATCHING',
    metrics: [{ label: 'Spacecraft Types', val: '4 Mission Classes' }, { label: 'Spec Matching', val: 'Automated' }],
  },
  {
    id: 'satellite_exploration',
    code: 'FT-06',
    title: 'SATELLITE EXPLORATION',
    subtitle: 'Interactive 3D Spacecraft Model',
    description: 'Inspect full 3D spacecraft geometry in an interactive viewport. Orbit, pan, zoom, and inspect real structural layouts before launch.',
    targetScreen: 'satellite',
    highlightTag: '3D ORBITAL VIEWPORT',
    metrics: [{ label: 'Lighting Models', val: 'True Solar Shadow' }, { label: 'Materials', val: 'Physically Based' }],
  },
  {
    id: 'exploded_view',
    code: 'FT-07',
    title: 'EXPLODED VIEW',
    subtitle: 'Subsystem Component Dissection',
    description: 'Dissect the spacecraft with an animated exploded view slider. Click individual modules to analyze their mass, power consumption, and failure modes.',
    targetScreen: 'satellite',
    highlightTag: 'MECHANICAL DISSECTION',
    metrics: [{ label: 'Subsystem Nodes', val: '6+ Core Units' }, { label: 'Separation Axis', val: 'Multi-Axis Expansion' }],
  },
  {
    id: 'mission_simulation',
    code: 'FT-08',
    title: 'MISSION SIMULATION',
    subtitle: 'Dynamic Space Hazards',
    description: 'Simulate orbital decay, solar proton storms, space debris conjunctions, battery cell degradation, and reaction wheel bearing anomalies.',
    targetScreen: 'scenarios',
    highlightTag: 'PHYSICS SIMULATOR',
    metrics: [{ label: 'Hazard Types', val: '16 Threat Scenarios' }, { label: 'Time Warp', val: '1x to 1000x' }],
  },
  {
    id: 'vyom_ai',
    code: 'FT-09',
    title: 'VYOM AI',
    subtitle: 'Autonomous Flight Advisor',
    description: 'Ask questions about orbital mechanics, mission architectures, or real-time anomalies. VYOM AI analyzes telemetry and delivers clear solutions.',
    targetScreen: 'ai',
    highlightTag: 'AUTONOMOUS ADVISOR',
    metrics: [{ label: 'Resolution Time', val: '6-Second Engine' }, { label: 'Domain Scope', val: 'Aerospace & Physics' }],
  },
];

// ── Quick Feature Guide Details for Section 5 ───────────────────
interface QuickGuideTopic {
  id: string;
  name: string;
  code: string;
  badge: string;
  targetScreen: AppScreen;
  whatItDoes: string;
  howToUseIt: string;
  whatYouCanLearn: string;
}

const QUICK_GUIDE_TOPICS: QuickGuideTopic[] = [
  {
    id: 'explore',
    name: 'Explore Missions',
    code: 'NAV-01',
    badge: 'ORBITAL VIEWER',
    targetScreen: 'universe',
    whatItDoes: 'Renders an interactive 3D model of celestial bodies and spacecraft trajectories across multiple orbital planes.',
    howToUseIt: 'Rotate the camera around planets, click on orbit paths to view apogee/perigee values, and switch viewpoints between celestial bodies.',
    whatYouCanLearn: 'How orbital mechanics, inclination angles, Keplerian elements, and gravitational regimes govern mission trajectories.',
  },
  {
    id: 'create',
    name: 'Create Mission',
    code: 'NAV-02',
    badge: 'MISSION ARCHITECT',
    targetScreen: 'onboarding',
    whatItDoes: 'Guides you through formulating a mission: naming your project, picking mission category, destination, launch site, and budget.',
    howToUseIt: 'Follow the numbered configuration steps, adjust mission parameters, review financial feasibility, and lock your flight profile.',
    whatYouCanLearn: 'How real-world aerospace engineers balance launch window constraints, payload mass, orbital requirements, and budget caps.',
  },
  {
    id: 'demo',
    name: 'Demo Mission',
    code: 'NAV-03',
    badge: 'READY FLIGHT',
    targetScreen: 'mission-control',
    whatItDoes: 'Loads a fully initialized spacecraft with pre-configured subsystems, telemetry feeds, and orbital parameters in one click.',
    howToUseIt: 'Click "Try Demo Mission" from anywhere on the landing or learn page to instantly enter the live Mission Control Room.',
    whatYouCanLearn: 'How flight controllers read high-speed telemetry, monitor battery cycles, track ground station acquisition, and verify health.',
  },
  {
    id: 'satellite_cfg',
    name: 'Satellite Configuration',
    code: 'NAV-04',
    badge: 'SPACECRAFT LAB',
    targetScreen: 'satellite',
    whatItDoes: 'Provides an interactive 3D inspection workbench for selecting satellite architectures, payloads, and exploded component layouts.',
    howToUseIt: 'Switch satellite archetypes, rotate the 3D model, drag the exploded view slider, and click subsystems for deep diagnostic readouts.',
    whatYouCanLearn: 'How spacecraft bus subsystems (power, ADCS, thermal, propulsion, comms) physically integrate and interact with one another.',
  },
  {
    id: 'twin',
    name: 'Digital Twin',
    code: 'NAV-05',
    badge: 'TELEMETRY MIRROR',
    targetScreen: 'digital-twin',
    whatItDoes: 'Maintains a live, synchronized digital model of spacecraft status, power generation, thermal envelopes, and subsystem health.',
    howToUseIt: 'View subsystem health status indicators, monitor real-time battery voltage, and track thermal gradients across solar and shadow passes.',
    whatYouCanLearn: 'Why digital twins are vital for modern space missions to predict hardware fatigue and test recovery actions safely before uplinking.',
  },
  {
    id: 'sim',
    name: 'Simulation',
    code: 'NAV-06',
    badge: 'HAZARD WORKBENCH',
    targetScreen: 'scenarios',
    whatItDoes: 'Injects dynamic space hazards into the active mission: solar flares, orbital debris conjunctions, sensor glitches, and leaks.',
    howToUseIt: 'Select a hazard from the scenario catalog, trigger it, and watch how spacecraft subsystems degrade and trigger autonomous alerts.',
    whatYouCanLearn: 'How critical single-point failures propagate across space systems and what emergency mitigation procedures are required.',
  },
  {
    id: 'ai',
    name: 'VYOM AI',
    code: 'NAV-07',
    badge: 'INTELLIGENT ADVISOR',
    targetScreen: 'ai',
    whatItDoes: 'An intelligent aerospace advisor capable of answering natural-language space engineering questions and diagnosing anomalies in seconds.',
    howToUseIt: 'Type any aerospace question or click pre-built prompts to request root-cause analysis, trajectory tips, or subsystem explanations.',
    whatYouCanLearn: 'Complex orbital mechanics, spacecraft subsystems, thermal control physics, and real-time failure mitigation explained in plain terms.',
  },
];

export function LearnScreen() {
  const setScreen = useMissionStore((s) => s.setScreen);
  const startMission = useMissionStore((s) => s.startMission);
  const setMissionConfig = useMissionStore((s) => s.setMissionConfig);

  // ── Local Interactive State ─────────────────────────────────────
  // Section 2 Interactive Walkthrough active step (1 to 6)
  const [activeStep, setActiveStep] = useState<number>(1);
  // Section 2 Step 4: Selected exploded component
  const [selectedCompId, setSelectedCompId] = useState<string>('solar_arrays');
  // Section 3 Feature Filter
  const [featureFilter, setFeatureFilter] = useState<string>('ALL');
  // Section 5 Quick Feature Guide active tab
  const [activeGuideId, setActiveGuideId] = useState<string>('explore');

  // Canvas starfield reference
  const canvasRef = useRef<HTMLCanvasElement | null>(null);

  // Smooth scroll to target element
  const scrollToSection = (id: string) => {
    const el = document.getElementById(id);
    if (!el) return;
    const top = el.getBoundingClientRect().top + window.scrollY - 70;
    window.scrollTo({ top: Math.max(0, top), behavior: 'smooth' });
  };

  // Pre-configured Demo Mission Launcher
  const handleLaunchDemo = () => {
    const profile = MISSION_PROFILES['orbital'];
    if (profile) setMissionConfig(profile.defaultConfig);
    startMission();
    setScreen('mission-control');
  };

  // Subtle drifting stars animation in canvas
  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    let animId: number;
    let width = (canvas.width = canvas.offsetWidth);
    let height = (canvas.height = canvas.offsetHeight);

    const handleResize = () => {
      if (!canvas) return;
      width = canvas.width = canvas.offsetWidth;
      height = canvas.height = canvas.offsetHeight;
    };
    window.addEventListener('resize', handleResize);

    const stars = Array.from({ length: 90 }, () => ({
      x: Math.random() * width,
      y: Math.random() * height,
      size: Math.random() * 1.5 + 0.5,
      alpha: Math.random() * 0.7 + 0.2,
      speed: Math.random() * 0.15 + 0.05,
    }));

    const render = () => {
      ctx.clearRect(0, 0, width, height);
      ctx.fillStyle = '#00d4ff';
      for (const s of stars) {
        s.y -= s.speed;
        if (s.y < 0) s.y = height;
        ctx.globalAlpha = s.alpha * 0.6;
        ctx.beginPath();
        ctx.arc(s.x, s.y, s.size, 0, Math.PI * 2);
        ctx.fill();
      }
      animId = requestAnimationFrame(render);
    };
    render();

    return () => {
      window.removeEventListener('resize', handleResize);
      cancelAnimationFrame(animId);
    };
  }, []);

  const selectedComponent =
    SATELLITE_COMPONENTS.find((c) => c.id === selectedCompId) || SATELLITE_COMPONENTS[0];

  const activeGuide =
    QUICK_GUIDE_TOPICS.find((g) => g.id === activeGuideId) || QUICK_GUIDE_TOPICS[0];

  const filteredFeatures =
    featureFilter === 'ALL'
      ? CORE_FEATURES
      : featureFilter === 'MISSIONS'
      ? CORE_FEATURES.filter((f) => ['explore_missions', 'create_mission', 'demo_mission'].includes(f.id))
      : featureFilter === 'SATELLITE'
      ? CORE_FEATURES.filter((f) => ['satellite_config', 'satellite_exploration', 'exploded_view'].includes(f.id))
      : CORE_FEATURES.filter((f) => ['digital_twin', 'mission_simulation', 'vyom_ai'].includes(f.id));

  return (
    <div
      style={{
        width: '100%',
        minHeight: '100vh',
        backgroundColor: '#020409',
        color: '#f0f4fc',
        fontFamily: 'var(--font-sans, "Inter", sans-serif)',
        overflowX: 'hidden',
        position: 'relative',
      }}
    >
      {/* Background Starfield Canvas */}
      <canvas
        ref={canvasRef}
        style={{
          position: 'fixed',
          top: 0,
          left: 0,
          width: '100%',
          height: '100%',
          pointerEvents: 'none',
          zIndex: 0,
          opacity: 0.65,
        }}
      />

      {/* Subtle Radial Atmosphere Gradients */}
      <div
        style={{
          position: 'fixed',
          top: '-20%',
          left: '15%',
          width: '70vw',
          height: '60vh',
          background: 'radial-gradient(circle at center, rgba(0, 212, 255, 0.07) 0%, transparent 70%)',
          pointerEvents: 'none',
          zIndex: 0,
        }}
      />
      <div
        style={{
          position: 'fixed',
          bottom: '-10%',
          right: '5%',
          width: '60vw',
          height: '50vh',
          background: 'radial-gradient(circle at center, rgba(155, 93, 229, 0.05) 0%, transparent 70%)',
          pointerEvents: 'none',
          zIndex: 0,
        }}
      />

      {/* ── STICKY AEROSPACE HEADER ───────────────────────────────── */}
      <header
        style={{
          position: 'sticky',
          top: 0,
          left: 0,
          width: '100%',
          zIndex: 1000,
          background: 'rgba(2, 4, 9, 0.88)',
          backdropFilter: 'blur(16px)',
          WebkitBackdropFilter: 'blur(16px)',
          borderBottom: '1px solid rgba(0, 212, 255, 0.15)',
          padding: '14px clamp(16px, 4vw, 48px)',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          gap: 16,
          boxSizing: 'border-box',
        }}
      >
        {/* Brand & Badge */}
        <div style={{ display: 'flex', alignItems: 'center', gap: 14 }}>
          <button
            onClick={() => setScreen('welcome')}
            style={{
              background: 'none',
              border: 'none',
              padding: 0,
              cursor: 'pointer',
              display: 'flex',
              alignItems: 'center',
              gap: 8,
            }}
          >
            <span
              style={{
                fontFamily: 'var(--font-editorial, "Syne", sans-serif)',
                fontSize: 20,
                fontWeight: 800,
                letterSpacing: '0.22em',
                color: '#ffffff',
              }}
            >
              VYOM
            </span>
          </button>
          <span style={{ width: 1, height: 16, backgroundColor: 'rgba(255,255,255,0.18)' }} />
          <div
            style={{
              display: 'flex',
              alignItems: 'center',
              gap: 6,
              background: 'rgba(0, 212, 255, 0.08)',
              border: '1px solid rgba(0, 212, 255, 0.25)',
              padding: '3px 9px',
              borderRadius: 3,
            }}
          >
            <span
              style={{
                width: 5,
                height: 5,
                borderRadius: '50%',
                backgroundColor: '#00d4ff',
                boxShadow: '0 0 6px #00d4ff',
              }}
            />
            <span
              style={{
                fontFamily: 'var(--font-mono, monospace)',
                fontSize: 9,
                letterSpacing: '0.14em',
                color: '#7cc4ff',
                textTransform: 'uppercase',
                fontWeight: 600,
              }}
            >
              LEARN & ONBOARDING CENTER
            </span>
          </div>
        </div>

        {/* Section Jump Links */}
        <nav
          style={{
            display: 'flex',
            alignItems: 'center',
            gap: 20,
            flexWrap: 'wrap',
          }}
          className="learn-nav-links"
        >
          <button
            onClick={() => scrollToSection('sec-learn-welcome')}
            style={{
              background: 'none',
              border: 'none',
              color: 'rgba(255,255,255,0.7)',
              cursor: 'pointer',
              fontFamily: 'var(--font-mono, monospace)',
              fontSize: 10,
              letterSpacing: '0.12em',
              transition: 'color 0.2s ease',
            }}
          >
            01 WELCOME
          </button>
          <button
            onClick={() => scrollToSection('sec-how-it-works')}
            style={{
              background: 'none',
              border: 'none',
              color: 'rgba(255,255,255,0.7)',
              cursor: 'pointer',
              fontFamily: 'var(--font-mono, monospace)',
              fontSize: 10,
              letterSpacing: '0.12em',
              transition: 'color 0.2s ease',
            }}
          >
            02 WORKFLOW
          </button>
          <button
            onClick={() => scrollToSection('sec-features')}
            style={{
              background: 'none',
              border: 'none',
              color: 'rgba(255,255,255,0.7)',
              cursor: 'pointer',
              fontFamily: 'var(--font-mono, monospace)',
              fontSize: 10,
              letterSpacing: '0.12em',
              transition: 'color 0.2s ease',
            }}
          >
            03 FEATURES
          </button>
          <button
            onClick={() => scrollToSection('sec-user-guide')}
            style={{
              background: 'none',
              border: 'none',
              color: 'rgba(255,255,255,0.7)',
              cursor: 'pointer',
              fontFamily: 'var(--font-mono, monospace)',
              fontSize: 10,
              letterSpacing: '0.12em',
              transition: 'color 0.2s ease',
            }}
          >
            04 FIRST-TIME GUIDE
          </button>
          <button
            onClick={() => scrollToSection('sec-quick-guide')}
            style={{
              background: 'none',
              border: 'none',
              color: 'rgba(255,255,255,0.7)',
              cursor: 'pointer',
              fontFamily: 'var(--font-mono, monospace)',
              fontSize: 10,
              letterSpacing: '0.12em',
              transition: 'color 0.2s ease',
            }}
          >
            05 QUICK GUIDE
          </button>
        </nav>

        {/* Action Header Buttons */}
        <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
          <button
            onClick={() => setScreen('welcome')}
            style={{
              background: 'rgba(255, 255, 255, 0.05)',
              color: 'rgba(255, 255, 255, 0.8)',
              border: '1px solid rgba(255, 255, 255, 0.12)',
              borderRadius: 3,
              padding: '7px 14px',
              fontFamily: 'var(--font-mono, monospace)',
              fontSize: 10,
              fontWeight: 600,
              letterSpacing: '0.12em',
              cursor: 'pointer',
              transition: 'all 0.2s ease',
            }}
          >
            MAIN SITE
          </button>
          <button
            onClick={() => setScreen('onboarding')}
            style={{
              background: '#00d4ff',
              color: '#020409',
              border: 'none',
              borderRadius: 3,
              padding: '7px 16px',
              fontFamily: 'var(--font-mono, monospace)',
              fontSize: 10,
              fontWeight: 700,
              letterSpacing: '0.12em',
              cursor: 'pointer',
              transition: 'all 0.2s ease',
              boxShadow: '0 0 14px rgba(0, 212, 255, 0.35)',
            }}
          >
            CREATE MISSION
          </button>
        </div>
      </header>

      {/* Main Container */}
      <main style={{ position: 'relative', zIndex: 1, maxWidth: 1320, margin: '0 auto', padding: '0 clamp(16px, 4vw, 48px)' }}>

        {/* ══════════════════════════════════════════════════════════════
            SECTION 1 — WELCOME TO VYOM
            ══════════════════════════════════════════════════════════════ */}
        <section
          id="sec-learn-welcome"
          style={{
            minHeight: '82vh',
            display: 'flex',
            flexDirection: 'column',
            justifyContent: 'center',
            paddingTop: 'clamp(48px, 8vh, 80px)',
            paddingBottom: 'clamp(48px, 8vh, 80px)',
            boxSizing: 'border-box',
          }}
        >
          {/* Eyebrow badge */}
          <div style={{ display: 'inline-flex', alignItems: 'center', gap: 8, marginBottom: 20 }}>
            <span style={{ color: '#00d4ff', fontFamily: 'var(--font-mono, monospace)', fontSize: 11, letterSpacing: '0.16em', fontWeight: 600 }}>
              01 // PLATFORM INTRODUCTION
            </span>
            <span style={{ width: 36, height: 1, backgroundColor: 'rgba(0, 212, 255, 0.4)' }} />
          </div>

          {/* Main Display Headline */}
          <h1
            style={{
              fontFamily: 'var(--font-editorial, "Syne", sans-serif)',
              fontSize: 'clamp(38px, 5.5vw, 68px)',
              fontWeight: 800,
              letterSpacing: '0.04em',
              lineHeight: 1.08,
              color: '#ffffff',
              margin: '0 0 16px 0',
            }}
          >
            WELCOME TO <span style={{ color: '#00d4ff', textShadow: '0 0 24px rgba(0, 212, 255, 0.45)' }}>VYOM</span>
          </h1>

          {/* Subtitle Quote */}
          <p
            style={{
              fontFamily: 'var(--font-serif, "Cormorant Garamond", Georgia, serif)',
              fontSize: 'clamp(20px, 2.5vw, 28px)',
              fontStyle: 'italic',
              color: '#7cc4ff',
              lineHeight: 1.35,
              maxWidth: 820,
              margin: '0 0 28px 0',
            }}
          >
            "Your gateway to exploring, creating and understanding space missions."
          </p>

          {/* Core Brief Explanation */}
          <p
            style={{
              fontFamily: 'var(--font-body, "Inter", sans-serif)',
              fontSize: 'clamp(14px, 1.15vw, 17px)',
              color: 'rgba(255, 255, 255, 0.78)',
              lineHeight: 1.68,
              maxWidth: 860,
              margin: '0 0 36px 0',
            }}
          >
            VYOM is an interactive Space Mission Digital Twin platform that helps users explore space missions,
            create mission scenarios, understand satellites, simulate mission conditions and learn through
            interactive visualizations.
          </p>

          {/* Hero CTA & Secondary Action */}
          <div style={{ display: 'flex', alignItems: 'center', gap: 16, flexWrap: 'wrap', marginBottom: 52 }}>
            <button
              onClick={() => setScreen('onboarding')}
              style={{
                background: 'linear-gradient(135deg, #00d4ff 0%, #0088cc 100%)',
                color: '#020409',
                border: 'none',
                borderRadius: 4,
                padding: '14px 28px',
                fontFamily: 'var(--font-mono, monospace)',
                fontSize: 12,
                fontWeight: 700,
                letterSpacing: '0.14em',
                cursor: 'pointer',
                display: 'inline-flex',
                alignItems: 'center',
                gap: 10,
                boxShadow: '0 4px 24px rgba(0, 212, 255, 0.35)',
                transition: 'all 0.25s ease',
              }}
            >
              START YOUR VYOM JOURNEY →
            </button>

            <button
              onClick={handleLaunchDemo}
              style={{
                background: 'rgba(3, 12, 28, 0.7)',
                color: '#7cc4ff',
                border: '1px solid rgba(0, 212, 255, 0.3)',
                borderRadius: 4,
                padding: '14px 24px',
                fontFamily: 'var(--font-mono, monospace)',
                fontSize: 12,
                fontWeight: 600,
                letterSpacing: '0.12em',
                cursor: 'pointer',
                transition: 'all 0.25s ease',
              }}
            >
              EXPERIENCE LIVE DEMO
            </button>

            <button
              onClick={() => scrollToSection('sec-how-it-works')}
              style={{
                background: 'none',
                color: 'rgba(255, 255, 255, 0.6)',
                border: 'none',
                padding: '14px 18px',
                fontFamily: 'var(--font-mono, monospace)',
                fontSize: 11,
                letterSpacing: '0.12em',
                cursor: 'pointer',
                textDecoration: 'underline',
                textUnderlineOffset: 4,
              }}
            >
              EXPLORE STEP-BY-STEP WORKFLOW ↓
            </button>
          </div>

          {/* High-Impact 2-Card Primer: What is VYOM & Why was VYOM created */}
          <div
            style={{
              display: 'grid',
              gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))',
              gap: 24,
            }}
          >
            {/* Card 1: What is VYOM? */}
            <div
              style={{
                background: 'rgba(4, 12, 26, 0.65)',
                border: '1px solid rgba(0, 212, 255, 0.2)',
                borderRadius: 8,
                padding: '28px 24px',
                backdropFilter: 'blur(8px)',
                position: 'relative',
              }}
            >
              <div
                style={{
                  fontFamily: 'var(--font-mono, monospace)',
                  fontSize: 10,
                  color: '#00d4ff',
                  letterSpacing: '0.16em',
                  marginBottom: 10,
                  fontWeight: 600,
                }}
              >
                QUESTION 01
              </div>
              <h3
                style={{
                  fontFamily: 'var(--font-display, "Orbitron", sans-serif)',
                  fontSize: 18,
                  fontWeight: 700,
                  letterSpacing: '0.06em',
                  color: '#ffffff',
                  marginBottom: 12,
                }}
              >
                WHAT IS VYOM?
              </h3>
              <p style={{ fontFamily: 'var(--font-body)', fontSize: 13, color: 'rgba(255,255,255,0.72)', lineHeight: 1.62 }}>
                VYOM is an interactive, unified digital twin environment that mirrors the complete lifecycle of space missions.
                From orbital mechanics and spacecraft component architectures to telemetry streams and real-time hazard responses,
                VYOM transforms abstract space mathematics into interactive, visual digital engineering.
              </p>
            </div>

            {/* Card 2: Why was VYOM created? */}
            <div
              style={{
                background: 'rgba(4, 12, 26, 0.65)',
                border: '1px solid rgba(155, 93, 229, 0.25)',
                borderRadius: 8,
                padding: '28px 24px',
                backdropFilter: 'blur(8px)',
                position: 'relative',
              }}
            >
              <div
                style={{
                  fontFamily: 'var(--font-mono, monospace)',
                  fontSize: 10,
                  color: '#b084f7',
                  letterSpacing: '0.16em',
                  marginBottom: 10,
                  fontWeight: 600,
                }}
              >
                QUESTION 02
              </div>
              <h3
                style={{
                  fontFamily: 'var(--font-display, "Orbitron", sans-serif)',
                  fontSize: 18,
                  fontWeight: 700,
                  letterSpacing: '0.06em',
                  color: '#ffffff',
                  marginBottom: 12,
                }}
              >
                WHY WAS VYOM CREATED?
              </h3>
              <p style={{ fontFamily: 'var(--font-body)', fontSize: 13, color: 'rgba(255,255,255,0.72)', lineHeight: 1.62 }}>
                Space exploration has historically been trapped behind siloed simulators, dense equations, and closed aerospace tools.
                VYOM was engineered to democratize mission understanding: giving engineers, students, and enthusiasts an intuitive,
                hands-on platform to design spacecraft, simulate orbital physics, and test autonomous flight intelligence.
              </p>
            </div>
          </div>
        </section>

        {/* ══════════════════════════════════════════════════════════════
            SECTION 2 — HOW VYOM WORKS (INTERACTIVE STEP-BY-STEP)
            ══════════════════════════════════════════════════════════════ */}
        <section
          id="sec-how-it-works"
          style={{
            paddingTop: 'clamp(48px, 8vh, 80px)',
            paddingBottom: 'clamp(48px, 8vh, 80px)',
            borderTop: '1px solid rgba(255, 255, 255, 0.08)',
          }}
        >
          {/* Eyebrow */}
          <div style={{ display: 'inline-flex', alignItems: 'center', gap: 8, marginBottom: 16 }}>
            <span style={{ color: '#00d4ff', fontFamily: 'var(--font-mono, monospace)', fontSize: 11, letterSpacing: '0.16em', fontWeight: 600 }}>
              02 // STEP-BY-STEP WALKTHROUGH
            </span>
            <span style={{ width: 36, height: 1, backgroundColor: 'rgba(0, 212, 255, 0.4)' }} />
          </div>

          <h2
            style={{
              fontFamily: 'var(--font-editorial, "Syne", sans-serif)',
              fontSize: 'clamp(32px, 4vw, 48px)',
              fontWeight: 800,
              letterSpacing: '0.04em',
              color: '#ffffff',
              margin: '0 0 12px 0',
            }}
          >
            HOW VYOM WORKS
          </h2>
          <p
            style={{
              fontFamily: 'var(--font-body)',
              fontSize: 'clamp(14px, 1.1vw, 16px)',
              color: 'rgba(255, 255, 255, 0.65)',
              maxWidth: 760,
              lineHeight: 1.6,
              margin: '0 0 36px 0',
            }}
          >
            Experience the complete end-to-end journey from initial orbital discovery to real-time AI advisory.
            Click any step below to expand its technical overview and visual preview.
          </p>

          {/* Interactive Step Navigator Tabs */}
          <div
            style={{
              display: 'grid',
              gridTemplateColumns: 'repeat(auto-fit, minmax(170px, 1fr))',
              gap: 10,
              marginBottom: 28,
            }}
          >
            {[
              { step: 1, title: 'EXPLORE', short: 'Discover Missions' },
              { step: 2, title: 'CREATE MISSION', short: 'Define Requirements' },
              { step: 3, title: 'CONFIGURE SATELLITE', short: 'Select 3D Spacecraft' },
              { step: 4, title: 'MODIFY SATELLITE', short: 'Exploded View Inspector' },
              { step: 5, title: 'SIMULATE', short: 'Hazard Scenarios' },
              { step: 6, title: 'VYOM AI', short: 'Intelligent Advisory' },
            ].map((item) => {
              const isCurrent = activeStep === item.step;
              return (
                <button
                  key={item.step}
                  onClick={() => setActiveStep(item.step)}
                  style={{
                    background: isCurrent ? 'rgba(0, 212, 255, 0.12)' : 'rgba(4, 10, 22, 0.55)',
                    border: isCurrent ? '1px solid #00d4ff' : '1px solid rgba(255, 255, 255, 0.08)',
                    borderRadius: 6,
                    padding: '14px 12px',
                    textAlign: 'left',
                    cursor: 'pointer',
                    transition: 'all 0.25s ease',
                    boxShadow: isCurrent ? '0 0 16px rgba(0, 212, 255, 0.2)' : 'none',
                  }}
                >
                  <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 6 }}>
                    <span
                      style={{
                        fontFamily: 'var(--font-mono)',
                        fontSize: 10,
                        fontWeight: 700,
                        color: isCurrent ? '#00d4ff' : 'rgba(255, 255, 255, 0.4)',
                        letterSpacing: '0.1em',
                      }}
                    >
                      STEP 0{item.step}
                    </span>
                    <span style={{ fontSize: 10, color: isCurrent ? '#00d4ff' : 'transparent' }}>◉</span>
                  </div>
                  <div
                    style={{
                      fontFamily: 'var(--font-display)',
                      fontSize: 11,
                      fontWeight: 700,
                      color: isCurrent ? '#ffffff' : 'rgba(255, 255, 255, 0.8)',
                      letterSpacing: '0.04em',
                      marginBottom: 4,
                    }}
                  >
                    {item.title}
                  </div>
                  <div style={{ fontFamily: 'var(--font-body)', fontSize: 10, color: 'rgba(255, 255, 255, 0.5)' }}>
                    {item.short}
                  </div>
                </button>
              );
            })}
          </div>

          {/* Active Step Detailed Expanded Card */}
          <div
            style={{
              background: 'rgba(3, 9, 20, 0.85)',
              border: '1px solid rgba(0, 212, 255, 0.25)',
              borderRadius: 8,
              padding: 'clamp(20px, 3.5vw, 36px)',
              backdropFilter: 'blur(12px)',
              position: 'relative',
              boxShadow: '0 8px 32px rgba(0, 0, 0, 0.45)',
            }}
          >
            {/* STEP 1: EXPLORE */}
            {activeStep === 1 && (
              <div>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: 12, marginBottom: 16 }}>
                  <div>
                    <span style={{ fontFamily: 'var(--font-mono)', fontSize: 11, color: '#00d4ff', letterSpacing: '0.14em' }}>
                      STEP 1 OF 6 // DISCOVERY PHASE
                    </span>
                    <h3 style={{ fontFamily: 'var(--font-display)', fontSize: 24, fontWeight: 700, color: '#fff', margin: '6px 0 0 0' }}>
                      EXPLORE MISSIONS
                    </h3>
                  </div>
                  <button
                    onClick={() => setScreen('universe')}
                    style={{
                      background: 'rgba(0, 212, 255, 0.1)',
                      border: '1px solid rgba(0, 212, 255, 0.4)',
                      borderRadius: 4,
                      color: '#00d4ff',
                      padding: '8px 16px',
                      fontFamily: 'var(--font-mono)',
                      fontSize: 11,
                      fontWeight: 600,
                      letterSpacing: '0.1em',
                      cursor: 'pointer',
                    }}
                  >
                    LAUNCH 3D UNIVERSE →
                  </button>
                </div>
                <p style={{ fontFamily: 'var(--font-body)', fontSize: 14, color: 'rgba(255,255,255,0.75)', lineHeight: 1.65, maxWidth: 840, marginBottom: 20 }}>
                  Discover space missions and understand their objectives. Explore real-world profiles like Earth Observation
                  (CartoSat-3D), Deep Space Relays (AstroSat-Next), Mars Aerocentric Insertion (Mangalyaan-II), and Human Spaceflight
                  (Gaganyaan-H1) in an interactive celestial map.
                </p>
                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))', gap: 14 }}>
                  <div style={{ background: 'rgba(0,0,0,0.35)', border: '1px solid rgba(255,255,255,0.06)', borderRadius: 6, padding: '16px 14px' }}>
                    <div style={{ fontFamily: 'var(--font-mono)', fontSize: 10, color: '#7cc4ff', marginBottom: 4 }}>OBJECTIVE RECOGNITION</div>
                    <div style={{ fontSize: 12, color: 'rgba(255,255,255,0.7)' }}>Understand mission goals, target celestial bodies, and expected operational lifetimes.</div>
                  </div>
                  <div style={{ background: 'rgba(0,0,0,0.35)', border: '1px solid rgba(255,255,255,0.06)', borderRadius: 6, padding: '16px 14px' }}>
                    <div style={{ fontFamily: 'var(--font-mono)', fontSize: 10, color: '#7cc4ff', marginBottom: 4 }}>ORBITAL VISUALIZATION</div>
                    <div style={{ fontSize: 12, color: 'rgba(255,255,255,0.7)' }}>Inspect apogee, perigee, inclination, and orbital velocity vectors in true 3D space.</div>
                  </div>
                  <div style={{ background: 'rgba(0,0,0,0.35)', border: '1px solid rgba(255,255,255,0.06)', borderRadius: 6, padding: '16px 14px' }}>
                    <div style={{ fontFamily: 'var(--font-mono)', fontSize: 10, color: '#7cc4ff', marginBottom: 4 }}>ONE-CLICK INITIATION</div>
                    <div style={{ fontSize: 12, color: 'rgba(255,255,255,0.7)' }}>Select any mission archetype to immediately inspect its telemetry or use it as a design template.</div>
                  </div>
                </div>
              </div>
            )}

            {/* STEP 2: CREATE A MISSION */}
            {activeStep === 2 && (
              <div>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: 12, marginBottom: 16 }}>
                  <div>
                    <span style={{ fontFamily: 'var(--font-mono)', fontSize: 11, color: '#00d4ff', letterSpacing: '0.14em' }}>
                      STEP 2 OF 6 // MISSION FORMULATION
                    </span>
                    <h3 style={{ fontFamily: 'var(--font-display)', fontSize: 24, fontWeight: 700, color: '#fff', margin: '6px 0 0 0' }}>
                      CREATE A MISSION
                    </h3>
                  </div>
                  <button
                    onClick={() => setScreen('onboarding')}
                    style={{
                      background: 'rgba(0, 212, 255, 0.1)',
                      border: '1px solid rgba(0, 212, 255, 0.4)',
                      borderRadius: 4,
                      color: '#00d4ff',
                      padding: '8px 16px',
                      fontFamily: 'var(--font-mono)',
                      fontSize: 11,
                      fontWeight: 600,
                      letterSpacing: '0.1em',
                      cursor: 'pointer',
                    }}
                  >
                    OPEN MISSION BUILDER →
                  </button>
                </div>
                <p style={{ fontFamily: 'var(--font-body)', fontSize: 14, color: 'rgba(255,255,255,0.75)', lineHeight: 1.65, maxWidth: 840, marginBottom: 20 }}>
                  Define or create your own mission based on your requirements. Specify mission name, choose destination
                  (Low Earth Orbit, Lunar Surface, Lagrange Point, or Mars), configure launch sites (e.g. Satish Dhawan Space Centre,
                  Kennedy Space Center), and balance financial budget allocations.
                </p>
                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))', gap: 14 }}>
                  <div style={{ background: 'rgba(0,0,0,0.35)', border: '1px solid rgba(255,255,255,0.06)', borderRadius: 6, padding: '16px 14px' }}>
                    <div style={{ fontFamily: 'var(--font-mono)', fontSize: 10, color: '#7cc4ff', marginBottom: 4 }}>PARAMETRIC CONSTRAINTS</div>
                    <div style={{ fontSize: 12, color: 'rgba(255,255,255,0.7)' }}>Align launch site latitude with target orbital inclinations to maximize launch rocket efficiency.</div>
                  </div>
                  <div style={{ background: 'rgba(0,0,0,0.35)', border: '1px solid rgba(255,255,255,0.06)', borderRadius: 6, padding: '16px 14px' }}>
                    <div style={{ fontFamily: 'var(--font-mono)', fontSize: 10, color: '#7cc4ff', marginBottom: 4 }}>FINANCIAL FEASIBILITY</div>
                    <div style={{ fontSize: 12, color: 'rgba(255,255,255,0.7)' }}>Live budget calculators estimate total expenditure in Crores with real-time contingency reserves.</div>
                  </div>
                  <div style={{ background: 'rgba(0,0,0,0.35)', border: '1px solid rgba(255,255,255,0.06)', borderRadius: 6, padding: '16px 14px' }}>
                    <div style={{ fontFamily: 'var(--font-mono)', fontSize: 10, color: '#7cc4ff', marginBottom: 4 }}>CREW ALLOCATION</div>
                    <div style={{ fontSize: 12, color: 'rgba(255,255,255,0.7)' }}>For crewed missions, define Commander, Specialist, and Medical Officer rosters with physiological profiles.</div>
                  </div>
                </div>
              </div>
            )}

            {/* STEP 3: SELECT & CONFIGURE SATELLITE */}
            {activeStep === 3 && (
              <div>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: 12, marginBottom: 16 }}>
                  <div>
                    <span style={{ fontFamily: 'var(--font-mono)', fontSize: 11, color: '#00d4ff', letterSpacing: '0.14em' }}>
                      STEP 3 OF 6 // SPACECRAFT ARCHITECTURE
                    </span>
                    <h3 style={{ fontFamily: 'var(--font-display)', fontSize: 24, fontWeight: 700, color: '#fff', margin: '6px 0 0 0' }}>
                      SELECT & CONFIGURE SATELLITE
                    </h3>
                  </div>
                  <button
                    onClick={() => setScreen('satellite')}
                    style={{
                      background: 'rgba(0, 212, 255, 0.1)',
                      border: '1px solid rgba(0, 212, 255, 0.4)',
                      borderRadius: 4,
                      color: '#00d4ff',
                      padding: '8px 16px',
                      fontFamily: 'var(--font-mono)',
                      fontSize: 11,
                      fontWeight: 600,
                      letterSpacing: '0.1em',
                      cursor: 'pointer',
                    }}
                  >
                    INSPECT 3D SATELLITES →
                  </button>
                </div>
                <p style={{ fontFamily: 'var(--font-body)', fontSize: 14, color: 'rgba(255,255,255,0.75)', lineHeight: 1.65, maxWidth: 840, marginBottom: 20 }}>
                  VYOM recommends suitable satellite options based on the mission. Users can explore an interactive 3D satellite
                  and view its components. Discover four specialized spacecraft classes: Earth Observation satellites with deployable
                  telescopes, High-Throughput Communication satellites, Deep-Space Planetary Probes, and Pressurized Crew Modules.
                </p>
                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))', gap: 14 }}>
                  <div style={{ background: 'rgba(0,0,0,0.35)', border: '1px solid rgba(255,255,255,0.06)', borderRadius: 6, padding: '16px 14px' }}>
                    <div style={{ fontFamily: 'var(--font-mono)', fontSize: 10, color: '#7cc4ff', marginBottom: 4 }}>MISSION MATCHING</div>
                    <div style={{ fontSize: 12, color: 'rgba(255,255,255,0.7)' }}>Intelligent algorithm scores compatibility between payload power draw and solar array surface area.</div>
                  </div>
                  <div style={{ background: 'rgba(0,0,0,0.35)', border: '1px solid rgba(255,255,255,0.06)', borderRadius: 6, padding: '16px 14px' }}>
                    <div style={{ fontFamily: 'var(--font-mono)', fontSize: 10, color: '#7cc4ff', marginBottom: 4 }}>3D STRUCTURAL INSPECTION</div>
                    <div style={{ fontSize: 12, color: 'rgba(255,255,255,0.7)' }}>Orbit and zoom around authentic 3D geometry with solar radiation illumination and panel reflections.</div>
                  </div>
                  <div style={{ background: 'rgba(0,0,0,0.35)', border: '1px solid rgba(255,255,255,0.06)', borderRadius: 6, padding: '16px 14px' }}>
                    <div style={{ fontFamily: 'var(--font-mono)', fontSize: 10, color: '#7cc4ff', marginBottom: 4 }}>MASS & POWER BUDGETING</div>
                    <div style={{ fontSize: 12, color: 'rgba(255,255,255,0.7)' }}>Review wet mass, dry mass, delta-V propulsion reserves, and bus voltage nominal ratings.</div>
                  </div>
                </div>
              </div>
            )}

            {/* STEP 4: MODIFY SATELLITE (EXPLODED VIEW) */}
            {activeStep === 4 && (
              <div>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: 12, marginBottom: 16 }}>
                  <div>
                    <span style={{ fontFamily: 'var(--font-mono)', fontSize: 11, color: '#00d4ff', letterSpacing: '0.14em' }}>
                      STEP 4 OF 6 // COMPONENT DISSECTION
                    </span>
                    <h3 style={{ fontFamily: 'var(--font-display)', fontSize: 24, fontWeight: 700, color: '#fff', margin: '6px 0 0 0' }}>
                      MODIFY SATELLITE & EXPLODED VIEW
                    </h3>
                  </div>
                  <button
                    onClick={() => setScreen('satellite')}
                    style={{
                      background: 'rgba(0, 212, 255, 0.1)',
                      border: '1px solid rgba(0, 212, 255, 0.4)',
                      borderRadius: 4,
                      color: '#00d4ff',
                      padding: '8px 16px',
                      fontFamily: 'var(--font-mono)',
                      fontSize: 11,
                      fontWeight: 600,
                      letterSpacing: '0.1em',
                      cursor: 'pointer',
                    }}
                  >
                    TEST EXPLODED VIEW IN 3D →
                  </button>
                </div>
                <p style={{ fontFamily: 'var(--font-body)', fontSize: 14, color: 'rgba(255,255,255,0.75)', lineHeight: 1.65, maxWidth: 840, marginBottom: 20 }}>
                  Explore the satellite in exploded view. Click individual components below to understand what the component does,
                  why it is required, its role in the mission, and available configuration options.
                </p>

                {/* Subsystem Component Selector Chips */}
                <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap', marginBottom: 20 }}>
                  {SATELLITE_COMPONENTS.map((c) => {
                    const isSelected = c.id === selectedCompId;
                    return (
                      <button
                        key={c.id}
                        onClick={() => setSelectedCompId(c.id)}
                        style={{
                          background: isSelected ? 'rgba(0, 212, 255, 0.2)' : 'rgba(0,0,0,0.4)',
                          border: isSelected ? '1px solid #00d4ff' : '1px solid rgba(255,255,255,0.1)',
                          color: isSelected ? '#ffffff' : 'rgba(255,255,255,0.6)',
                          borderRadius: 4,
                          padding: '6px 14px',
                          fontFamily: 'var(--font-mono)',
                          fontSize: 11,
                          fontWeight: 600,
                          cursor: 'pointer',
                          transition: 'all 0.2s ease',
                        }}
                      >
                        {c.name.split(' ')[0]} {c.name.split(' ')[1]}
                      </button>
                    );
                  })}
                </div>

                {/* Detailed 4-Point Inspector for Selected Component */}
                <div
                  style={{
                    background: 'rgba(2, 6, 14, 0.9)',
                    border: '1px solid rgba(0, 212, 255, 0.2)',
                    borderRadius: 6,
                    padding: '20px 22px',
                  }}
                >
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 14 }}>
                    <div>
                      <span style={{ fontFamily: 'var(--font-mono)', fontSize: 10, color: '#7cc4ff', letterSpacing: '0.12em' }}>
                        {selectedComponent.techCode} // {selectedComponent.system.toUpperCase()}
                      </span>
                      <h4 style={{ fontFamily: 'var(--font-display)', fontSize: 16, fontWeight: 700, color: '#00d4ff', margin: '4px 0 0 0' }}>
                        {selectedComponent.name}
                      </h4>
                    </div>
                    <span style={{ fontFamily: 'var(--font-mono)', fontSize: 10, color: '#00ff88', background: 'rgba(0,255,136,0.1)', padding: '3px 8px', borderRadius: 3, border: '1px solid rgba(0,255,136,0.2)' }}>
                      STATUS: NOMINAL
                    </span>
                  </div>

                  <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: 16 }}>
                    {/* 1. What the component does */}
                    <div style={{ background: 'rgba(255,255,255,0.02)', padding: '12px 14px', borderRadius: 4, borderLeft: '2px solid #00d4ff' }}>
                      <div style={{ fontFamily: 'var(--font-mono)', fontSize: 10, color: '#00d4ff', letterSpacing: '0.1em', marginBottom: 4 }}>
                        1. WHAT THE COMPONENT DOES
                      </div>
                      <div style={{ fontSize: 12, color: 'rgba(255,255,255,0.85)', lineHeight: 1.55 }}>
                        {selectedComponent.whatItDoes}
                      </div>
                    </div>

                    {/* 2. Why it is required */}
                    <div style={{ background: 'rgba(255,255,255,0.02)', padding: '12px 14px', borderRadius: 4, borderLeft: '2px solid #7cc4ff' }}>
                      <div style={{ fontFamily: 'var(--font-mono)', fontSize: 10, color: '#7cc4ff', letterSpacing: '0.1em', marginBottom: 4 }}>
                        2. WHY IT IS REQUIRED
                      </div>
                      <div style={{ fontSize: 12, color: 'rgba(255,255,255,0.85)', lineHeight: 1.55 }}>
                        {selectedComponent.whyRequired}
                      </div>
                    </div>

                    {/* 3. Its role in the mission */}
                    <div style={{ background: 'rgba(255,255,255,0.02)', padding: '12px 14px', borderRadius: 4, borderLeft: '2px solid #b084f7' }}>
                      <div style={{ fontFamily: 'var(--font-mono)', fontSize: 10, color: '#b084f7', letterSpacing: '0.1em', marginBottom: 4 }}>
                        3. ROLE IN THE MISSION
                      </div>
                      <div style={{ fontSize: 12, color: 'rgba(255,255,255,0.85)', lineHeight: 1.55 }}>
                        {selectedComponent.missionRole}
                      </div>
                    </div>

                    {/* 4. Available configuration options */}
                    <div style={{ background: 'rgba(255,255,255,0.02)', padding: '12px 14px', borderRadius: 4, borderLeft: '2px solid #00ff88' }}>
                      <div style={{ fontFamily: 'var(--font-mono)', fontSize: 10, color: '#00ff88', letterSpacing: '0.1em', marginBottom: 6 }}>
                        4. CONFIGURATION OPTIONS
                      </div>
                      <ul style={{ margin: 0, paddingLeft: 16, fontSize: 11, color: 'rgba(255,255,255,0.75)', lineHeight: 1.6 }}>
                        {selectedComponent.configOptions.map((opt, idx) => (
                          <li key={idx}>{opt}</li>
                        ))}
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            )}

            {/* STEP 5: SIMULATE */}
            {activeStep === 5 && (
              <div>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: 12, marginBottom: 16 }}>
                  <div>
                    <span style={{ fontFamily: 'var(--font-mono)', fontSize: 11, color: '#00d4ff', letterSpacing: '0.14em' }}>
                      STEP 5 OF 6 // MISSION EXECUTION & HAZARDS
                    </span>
                    <h3 style={{ fontFamily: 'var(--font-display)', fontSize: 24, fontWeight: 700, color: '#fff', margin: '6px 0 0 0' }}>
                      SIMULATE & MONITOR
                    </h3>
                  </div>
                  <button
                    onClick={() => setScreen('scenarios')}
                    style={{
                      background: 'rgba(0, 212, 255, 0.1)',
                      border: '1px solid rgba(0, 212, 255, 0.4)',
                      borderRadius: 4,
                      color: '#00d4ff',
                      padding: '8px 16px',
                      fontFamily: 'var(--font-mono)',
                      fontSize: 11,
                      fontWeight: 600,
                      letterSpacing: '0.1em',
                      cursor: 'pointer',
                    }}
                  >
                    ENTER DANGER SIMULATOR →
                  </button>
                </div>
                <p style={{ fontFamily: 'var(--font-body)', fontSize: 14, color: 'rgba(255,255,255,0.75)', lineHeight: 1.65, maxWidth: 840, marginBottom: 20 }}>
                  Visualize mission scenarios and understand possible outcomes. Control simulation speeds from 1x to 1000x,
                  track telemetry health parameters across orbital revolutions, and inject real space hazards (solar radiation bursts,
                  orbital debris, reaction wheel stutters) to observe spacecraft degradation and autonomous mitigation.
                </p>
                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))', gap: 14 }}>
                  <div style={{ background: 'rgba(0,0,0,0.35)', border: '1px solid rgba(255,255,255,0.06)', borderRadius: 6, padding: '16px 14px' }}>
                    <div style={{ fontFamily: 'var(--font-mono)', fontSize: 10, color: '#7cc4ff', marginBottom: 4 }}>HAZARD PROPAGATION</div>
                    <div style={{ fontSize: 12, color: 'rgba(255,255,255,0.7)' }}>Observe how external thermal radiation cascades into battery overheating and payload throttling.</div>
                  </div>
                  <div style={{ background: 'rgba(0,0,0,0.35)', border: '1px solid rgba(255,255,255,0.06)', borderRadius: 6, padding: '16px 14px' }}>
                    <div style={{ fontFamily: 'var(--font-mono)', fontSize: 10, color: '#7cc4ff', marginBottom: 4 }}>BLACK BOX TELEMETRY</div>
                    <div style={{ fontSize: 12, color: 'rgba(255,255,255,0.7)' }}>Immutable event logging captures every command, sensor glitch, and autonomous recovery attempt.</div>
                  </div>
                  <div style={{ background: 'rgba(0,0,0,0.35)', border: '1px solid rgba(255,255,255,0.06)', borderRadius: 6, padding: '16px 14px' }}>
                    <div style={{ fontFamily: 'var(--font-mono)', fontSize: 10, color: '#7cc4ff', marginBottom: 4 }}>DISPOSITION & FAREWELL</div>
                    <div style={{ fontSize: 12, color: 'rgba(255,255,255,0.7)' }}>Conclude mission lifetimes with controlled atmospheric re-entry or graveyard orbit transfers.</div>
                  </div>
                </div>
              </div>
            )}

            {/* STEP 6: LEARN WITH VYOM AI */}
            {activeStep === 6 && (
              <div>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: 12, marginBottom: 16 }}>
                  <div>
                    <span style={{ fontFamily: 'var(--font-mono)', fontSize: 11, color: '#9b5de5', letterSpacing: '0.14em' }}>
                      STEP 6 OF 6 // INTELLIGENT ONBOARD ADVISOR
                    </span>
                    <h3 style={{ fontFamily: 'var(--font-display)', fontSize: 24, fontWeight: 700, color: '#fff', margin: '6px 0 0 0' }}>
                      LEARN WITH VYOM AI
                    </h3>
                  </div>
                  <button
                    onClick={() => setScreen('ai')}
                    style={{
                      background: 'rgba(155, 93, 229, 0.15)',
                      border: '1px solid rgba(155, 93, 229, 0.45)',
                      borderRadius: 4,
                      color: '#b084f7',
                      padding: '8px 16px',
                      fontFamily: 'var(--font-mono)',
                      fontSize: 11,
                      fontWeight: 600,
                      letterSpacing: '0.1em',
                      cursor: 'pointer',
                    }}
                  >
                    CONSULT VYOM AI NOW →
                  </button>
                </div>
                <p style={{ fontFamily: 'var(--font-body)', fontSize: 14, color: 'rgba(255,255,255,0.75)', lineHeight: 1.65, maxWidth: 840, marginBottom: 20 }}>
                  Ask questions and receive simple explanations about missions, satellites and space concepts.
                  VYOM AI acts as your resident flight director: diagnosing active anomalies, providing recovery checklists,
                  and answering complex aerospace physics questions in clear, conversational language.
                </p>
                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))', gap: 14 }}>
                  <div style={{ background: 'rgba(0,0,0,0.35)', border: '1px solid rgba(155,93,229,0.15)', borderRadius: 6, padding: '16px 14px' }}>
                    <div style={{ fontFamily: 'var(--font-mono)', fontSize: 10, color: '#b084f7', marginBottom: 4 }}>ROOT-CAUSE DIAGNOSIS</div>
                    <div style={{ fontSize: 12, color: 'rgba(255,255,255,0.7)' }}>Pinpoints exact component anomalies and suggests verified procedure steps within 6 seconds.</div>
                  </div>
                  <div style={{ background: 'rgba(0,0,0,0.35)', border: '1px solid rgba(155,93,229,0.15)', borderRadius: 6, padding: '16px 14px' }}>
                    <div style={{ fontFamily: 'var(--font-mono)', fontSize: 10, color: '#b084f7', marginBottom: 4 }}>NATURAL LANGUAGE QA</div>
                    <div style={{ fontSize: 12, color: 'rgba(255,255,255,0.7)' }}>Ask: "Why do satellites use hypergolic propellants?" or "What is sun-synchronous orbit?"</div>
                  </div>
                  <div style={{ background: 'rgba(0,0,0,0.35)', border: '1px solid rgba(155,93,229,0.15)', borderRadius: 6, padding: '16px 14px' }}>
                    <div style={{ fontFamily: 'var(--font-mono)', fontSize: 10, color: '#b084f7', marginBottom: 4 }}>DECISION EXPLANABILITY</div>
                    <div style={{ fontSize: 12, color: 'rgba(255,255,255,0.7)' }}>Shows neural activation confidence, telemetry correlation, and alternate contingency branches.</div>
                  </div>
                </div>
              </div>
            )}

            {/* Stepper Navigation Controls */}
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginTop: 28, paddingTop: 18, borderTop: '1px solid rgba(255,255,255,0.08)' }}>
              <button
                disabled={activeStep === 1}
                onClick={() => setActiveStep((prev) => Math.max(1, prev - 1))}
                style={{
                  background: 'none',
                  border: '1px solid rgba(255,255,255,0.15)',
                  borderRadius: 4,
                  color: activeStep === 1 ? 'rgba(255,255,255,0.2)' : 'rgba(255,255,255,0.8)',
                  padding: '7px 14px',
                  fontFamily: 'var(--font-mono)',
                  fontSize: 10,
                  cursor: activeStep === 1 ? 'not-allowed' : 'pointer',
                }}
              >
                ← PREVIOUS STEP
              </button>
              <div style={{ fontFamily: 'var(--font-mono)', fontSize: 11, color: 'rgba(255,255,255,0.4)' }}>
                STEP {activeStep} OF 6
              </div>
              <button
                disabled={activeStep === 6}
                onClick={() => setActiveStep((prev) => Math.min(6, prev + 1))}
                style={{
                  background: activeStep === 6 ? 'none' : 'rgba(0,212,255,0.15)',
                  border: activeStep === 6 ? '1px solid rgba(255,255,255,0.15)' : '1px solid rgba(0,212,255,0.4)',
                  borderRadius: 4,
                  color: activeStep === 6 ? 'rgba(255,255,255,0.2)' : '#00d4ff',
                  padding: '7px 14px',
                  fontFamily: 'var(--font-mono)',
                  fontSize: 10,
                  fontWeight: 600,
                  cursor: activeStep === 6 ? 'not-allowed' : 'pointer',
                }}
              >
                NEXT STEP →
              </button>
            </div>
          </div>
        </section>

        {/* ══════════════════════════════════════════════════════════════
            SECTION 3 — VYOM FEATURES
            ══════════════════════════════════════════════════════════════ */}
        <section
          id="sec-features"
          style={{
            paddingTop: 'clamp(48px, 8vh, 80px)',
            paddingBottom: 'clamp(48px, 8vh, 80px)',
            borderTop: '1px solid rgba(255, 255, 255, 0.08)',
          }}
        >
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', flexWrap: 'wrap', gap: 16, marginBottom: 28 }}>
            <div>
              <div style={{ display: 'inline-flex', alignItems: 'center', gap: 8, marginBottom: 12 }}>
                <span style={{ color: '#00d4ff', fontFamily: 'var(--font-mono, monospace)', fontSize: 11, letterSpacing: '0.16em', fontWeight: 600 }}>
                  03 // PLATFORM CAPABILITIES
                </span>
                <span style={{ width: 36, height: 1, backgroundColor: 'rgba(0, 212, 255, 0.4)' }} />
              </div>
              <h2
                style={{
                  fontFamily: 'var(--font-editorial, "Syne", sans-serif)',
                  fontSize: 'clamp(32px, 4vw, 48px)',
                  fontWeight: 800,
                  letterSpacing: '0.04em',
                  color: '#ffffff',
                  margin: 0,
                }}
              >
                VYOM FEATURES
              </h2>
            </div>

            {/* Feature Filter Buttons */}
            <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
              {[
                { label: 'ALL (9)', val: 'ALL' },
                { label: 'MISSIONS', val: 'MISSIONS' },
                { label: 'SATELLITE 3D', val: 'SATELLITE' },
                { label: 'SIM & AI', val: 'SIM_AI' },
              ].map((tab) => (
                <button
                  key={tab.val}
                  onClick={() => setFeatureFilter(tab.val)}
                  style={{
                    background: featureFilter === tab.val ? 'rgba(0,212,255,0.15)' : 'rgba(255,255,255,0.03)',
                    border: featureFilter === tab.val ? '1px solid #00d4ff' : '1px solid rgba(255,255,255,0.1)',
                    color: featureFilter === tab.val ? '#00d4ff' : 'rgba(255,255,255,0.65)',
                    borderRadius: 4,
                    padding: '6px 12px',
                    fontFamily: 'var(--font-mono)',
                    fontSize: 10,
                    fontWeight: 600,
                    letterSpacing: '0.1em',
                    cursor: 'pointer',
                    transition: 'all 0.2s ease',
                  }}
                >
                  {tab.label}
                </button>
              ))}
            </div>
          </div>

          <p
            style={{
              fontFamily: 'var(--font-body)',
              fontSize: 14,
              color: 'rgba(255, 255, 255, 0.65)',
              maxWidth: 760,
              lineHeight: 1.6,
              margin: '0 0 36px 0',
            }}
          >
            Explore the core architectural modules engineered into VYOM. Every feature connects directly to real mathematical models,
            3D WebGL renderers, and aerospace telemetry processors.
          </p>

          {/* Features Grid (9 cards) */}
          <div
            style={{
              display: 'grid',
              gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))',
              gap: 20,
            }}
          >
            {filteredFeatures.map((f) => (
              <div
                key={f.id}
                style={{
                  background: 'rgba(4, 11, 24, 0.6)',
                  border: '1px solid rgba(0, 212, 255, 0.16)',
                  borderRadius: 8,
                  padding: '26px 22px',
                  display: 'flex',
                  flexDirection: 'column',
                  justifyContent: 'space-between',
                  transition: 'transform 0.25s ease, border-color 0.25s ease, box-shadow 0.25s ease',
                  position: 'relative',
                  overflow: 'hidden',
                }}
              >
                {/* Top Header info */}
                <div>
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 14 }}>
                    <span
                      style={{
                        fontFamily: 'var(--font-mono)',
                        fontSize: 9,
                        color: '#7cc4ff',
                        background: 'rgba(0, 212, 255, 0.08)',
                        padding: '3px 8px',
                        borderRadius: 3,
                        border: '1px solid rgba(0, 212, 255, 0.2)',
                        letterSpacing: '0.1em',
                      }}
                    >
                      {f.highlightTag}
                    </span>
                    <span
                      style={{
                        fontFamily: 'var(--font-mono)',
                        fontSize: 10,
                        color: 'rgba(255, 255, 255, 0.35)',
                        letterSpacing: '0.14em',
                      }}
                    >
                      {f.code}
                    </span>
                  </div>

                  <h3
                    style={{
                      fontFamily: 'var(--font-display)',
                      fontSize: 16,
                      fontWeight: 700,
                      letterSpacing: '0.04em',
                      color: '#ffffff',
                      marginBottom: 4,
                    }}
                  >
                    {f.title}
                  </h3>
                  <div
                    style={{
                      fontFamily: 'var(--font-mono)',
                      fontSize: 10,
                      color: '#00d4ff',
                      letterSpacing: '0.08em',
                      marginBottom: 12,
                    }}
                  >
                    {f.subtitle}
                  </div>

                  <p
                    style={{
                      fontFamily: 'var(--font-body)',
                      fontSize: 12,
                      color: 'rgba(255, 255, 255, 0.7)',
                      lineHeight: 1.6,
                      margin: '0 0 20px 0',
                    }}
                  >
                    {f.description}
                  </p>
                </div>

                {/* Metrics & Launch CTA */}
                <div>
                  <div
                    style={{
                      display: 'grid',
                      gridTemplateColumns: '1fr 1fr',
                      gap: 8,
                      padding: '10px 12px',
                      background: 'rgba(0,0,0,0.3)',
                      borderRadius: 4,
                      marginBottom: 16,
                      border: '1px solid rgba(255,255,255,0.04)',
                    }}
                  >
                    {f.metrics.map((m, i) => (
                      <div key={i}>
                        <div style={{ fontFamily: 'var(--font-mono)', fontSize: 9, color: 'rgba(255,255,255,0.4)', textTransform: 'uppercase' }}>
                          {m.label}
                        </div>
                        <div style={{ fontFamily: 'var(--font-mono)', fontSize: 11, fontWeight: 700, color: '#f0f4fc' }}>
                          {m.val}
                        </div>
                      </div>
                    ))}
                  </div>

                  <button
                    onClick={() => {
                      if (f.id === 'demo_mission') {
                        handleLaunchDemo();
                      } else {
                        setScreen(f.targetScreen);
                      }
                    }}
                    style={{
                      width: '100%',
                      background: 'rgba(0, 212, 255, 0.08)',
                      border: '1px solid rgba(0, 212, 255, 0.3)',
                      borderRadius: 4,
                      color: '#00d4ff',
                      padding: '8px 14px',
                      fontFamily: 'var(--font-mono)',
                      fontSize: 10,
                      fontWeight: 600,
                      letterSpacing: '0.12em',
                      cursor: 'pointer',
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                      gap: 6,
                      transition: 'all 0.2s ease',
                    }}
                  >
                    OPEN {f.title} →
                  </button>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* ══════════════════════════════════════════════════════════════
            SECTION 4 — FIRST TIME USER GUIDE
            ══════════════════════════════════════════════════════════════ */}
        <section
          id="sec-user-guide"
          style={{
            paddingTop: 'clamp(48px, 8vh, 80px)',
            paddingBottom: 'clamp(48px, 8vh, 80px)',
            borderTop: '1px solid rgba(255, 255, 255, 0.08)',
          }}
        >
          {/* Eyebrow */}
          <div style={{ display: 'inline-flex', alignItems: 'center', gap: 8, marginBottom: 12 }}>
            <span style={{ color: '#00d4ff', fontFamily: 'var(--font-mono, monospace)', fontSize: 11, letterSpacing: '0.16em', fontWeight: 600 }}>
              04 // ONBOARDING ROADMAP
            </span>
            <span style={{ width: 36, height: 1, backgroundColor: 'rgba(0, 212, 255, 0.4)' }} />
          </div>

          <h2
            style={{
              fontFamily: 'var(--font-editorial, "Syne", sans-serif)',
              fontSize: 'clamp(32px, 4vw, 48px)',
              fontWeight: 800,
              letterSpacing: '0.04em',
              color: '#ffffff',
              margin: '0 0 12px 0',
            }}
          >
            NEW TO VYOM?
          </h2>
          <p
            style={{
              fontFamily: 'var(--font-body)',
              fontSize: 14,
              color: 'rgba(255, 255, 255, 0.65)',
              maxWidth: 760,
              lineHeight: 1.6,
              margin: '0 0 40px 0',
            }}
          >
            Follow this simple, sequential 6-step guided path to become comfortable with the platform in under five minutes.
          </p>

          {/* 6 Guided Cards */}
          <div
            style={{
              display: 'grid',
              gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))',
              gap: 20,
              marginBottom: 44,
            }}
          >
            {[
              {
                num: '01',
                title: 'START WITH A DEMO MISSION',
                desc: 'Explore a pre-built mission to understand the platform without configuring complex parameters.',
                tip: 'Recommended first step for total beginners.',
                badge: '2 MIN READOUT',
                actionLabel: 'LAUNCH DEMO NOW',
                onAction: handleLaunchDemo,
              },
              {
                num: '02',
                title: 'EXPLORE THE MISSION',
                desc: 'Interact with mission data and visualizations in the real-time Mission Control room.',
                tip: 'Inspect 3D trajectory trails, altitude curves, and power meters.',
                badge: 'INTERACTIVE METRICS',
                actionLabel: 'VIEW CONTROL ROOM',
                onAction: () => setScreen('mission-control'),
              },
              {
                num: '03',
                title: 'TRY CREATE MISSION',
                desc: 'Create your own mission scenario: choose launch site, mission destination, and budget envelope.',
                tip: 'Formulate orbital parameters and payload architectures.',
                badge: 'MISSION BUILDER',
                actionLabel: 'START BUILDER',
                onAction: () => setScreen('onboarding'),
              },
              {
                num: '04',
                title: 'CONFIGURE YOUR SATELLITE',
                desc: 'Select and explore the satellite recommended for your mission with 3D exploded view diagnostics.',
                tip: 'Inspect solar arrays, optics, high-gain antennas, and thrusters.',
                badge: '3D WORKBENCH',
                actionLabel: 'CONFIG SATELLITE',
                onAction: () => setScreen('satellite'),
              },
              {
                num: '05',
                title: 'ENTER SIMULATION',
                desc: 'Visualize how your mission progresses over hours and days with interactive time warp acceleration.',
                tip: 'Trigger radiation storms or orbital debris conjunctions to test resilience.',
                badge: 'PHYSICS ENGINE',
                onAction: () => setScreen('scenarios'),
                actionLabel: 'RUN SIMULATION',
              },
              {
                num: '06',
                title: 'ASK VYOM AI',
                desc: 'Ask questions whenever you need help understanding space mission terminology or subsystem behavior.',
                tip: 'Type in plain English or select from suggested aerospace prompts.',
                badge: 'AI ASSISTANT',
                actionLabel: 'CONSULT AI',
                onAction: () => setScreen('ai'),
              },
            ].map((step) => (
              <div
                key={step.num}
                style={{
                  background: step.num === '01' ? 'rgba(0, 212, 255, 0.08)' : 'rgba(3, 9, 20, 0.65)',
                  border: step.num === '01' ? '1px solid #00d4ff' : '1px solid rgba(255, 255, 255, 0.08)',
                  borderRadius: 8,
                  padding: '26px 22px',
                  display: 'flex',
                  flexDirection: 'column',
                  justifyContent: 'space-between',
                  boxShadow: step.num === '01' ? '0 0 24px rgba(0, 212, 255, 0.15)' : 'none',
                }}
              >
                <div>
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 14 }}>
                    <span
                      style={{
                        fontFamily: 'var(--font-mono)',
                        fontSize: 16,
                        fontWeight: 800,
                        color: step.num === '01' ? '#00d4ff' : 'rgba(255, 255, 255, 0.4)',
                        letterSpacing: '0.1em',
                      }}
                    >
                      {step.num}
                    </span>
                    <span
                      style={{
                        fontFamily: 'var(--font-mono)',
                        fontSize: 9,
                        color: '#7cc4ff',
                        background: 'rgba(0, 212, 255, 0.08)',
                        padding: '2px 7px',
                        borderRadius: 3,
                        border: '1px solid rgba(0, 212, 255, 0.2)',
                      }}
                    >
                      {step.badge}
                    </span>
                  </div>

                  <h3
                    style={{
                      fontFamily: 'var(--font-display)',
                      fontSize: 15,
                      fontWeight: 700,
                      color: '#ffffff',
                      marginBottom: 8,
                      letterSpacing: '0.04em',
                    }}
                  >
                    {step.title}
                  </h3>

                  <p style={{ fontFamily: 'var(--font-body)', fontSize: 13, color: 'rgba(255,255,255,0.72)', lineHeight: 1.55, margin: '0 0 12px 0' }}>
                    {step.desc}
                  </p>

                  <div
                    style={{
                      fontFamily: 'var(--font-mono)',
                      fontSize: 10,
                      color: '#00ff88',
                      background: 'rgba(0,255,136,0.06)',
                      border: '1px solid rgba(0,255,136,0.15)',
                      padding: '6px 10px',
                      borderRadius: 4,
                      marginBottom: 18,
                    }}
                  >
                    PRO TIP: {step.tip}
                  </div>
                </div>

                <button
                  onClick={step.onAction}
                  style={{
                    background: step.num === '01' ? '#00d4ff' : 'rgba(255,255,255,0.05)',
                    border: step.num === '01' ? 'none' : '1px solid rgba(255,255,255,0.15)',
                    color: step.num === '01' ? '#020409' : '#ffffff',
                    borderRadius: 4,
                    padding: '8px 12px',
                    fontFamily: 'var(--font-mono)',
                    fontSize: 10,
                    fontWeight: 700,
                    letterSpacing: '0.12em',
                    cursor: 'pointer',
                    transition: 'all 0.2s ease',
                  }}
                >
                  {step.actionLabel} →
                </button>
              </div>
            ))}
          </div>

          {/* Prominent CTA */}
          <div style={{ textAlign: 'center' }}>
            <button
              onClick={handleLaunchDemo}
              style={{
                background: 'linear-gradient(135deg, #00d4ff 0%, #0077b6 100%)',
                color: '#020409',
                border: 'none',
                borderRadius: 4,
                padding: '16px 36px',
                fontFamily: 'var(--font-mono, monospace)',
                fontSize: 13,
                fontWeight: 800,
                letterSpacing: '0.16em',
                cursor: 'pointer',
                display: 'inline-flex',
                alignItems: 'center',
                gap: 12,
                boxShadow: '0 0 30px rgba(0, 212, 255, 0.4)',
                transition: 'all 0.25s ease',
              }}
            >
              TRY YOUR FIRST MISSION →
            </button>
          </div>
        </section>

        {/* ══════════════════════════════════════════════════════════════
            SECTION 5 — QUICK FEATURE GUIDE
            ══════════════════════════════════════════════════════════════ */}
        <section
          id="sec-quick-guide"
          style={{
            paddingTop: 'clamp(48px, 8vh, 80px)',
            paddingBottom: 'clamp(48px, 8vh, 80px)',
            borderTop: '1px solid rgba(255, 255, 255, 0.08)',
          }}
        >
          {/* Eyebrow */}
          <div style={{ display: 'inline-flex', alignItems: 'center', gap: 8, marginBottom: 12 }}>
            <span style={{ color: '#00d4ff', fontFamily: 'var(--font-mono, monospace)', fontSize: 11, letterSpacing: '0.16em', fontWeight: 600 }}>
              05 // INTERACTIVE REFERENCE
            </span>
            <span style={{ width: 36, height: 1, backgroundColor: 'rgba(0, 212, 255, 0.4)' }} />
          </div>

          <h2
            style={{
              fontFamily: 'var(--font-editorial, "Syne", sans-serif)',
              fontSize: 'clamp(32px, 4vw, 48px)',
              fontWeight: 800,
              letterSpacing: '0.04em',
              color: '#ffffff',
              margin: '0 0 12px 0',
            }}
          >
            QUICK FEATURE GUIDE
          </h2>
          <p
            style={{
              fontFamily: 'var(--font-body)',
              fontSize: 14,
              color: 'rgba(255, 255, 255, 0.65)',
              maxWidth: 760,
              lineHeight: 1.6,
              margin: '0 0 32px 0',
            }}
          >
            Select any feature below to get a concise breakdown of what it does, how to use it, and what you can learn from it.
          </p>

          {/* Selector Tabs (7 items) */}
          <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap', marginBottom: 24 }}>
            {QUICK_GUIDE_TOPICS.map((t) => {
              const isSelected = t.id === activeGuideId;
              return (
                <button
                  key={t.id}
                  onClick={() => setActiveGuideId(t.id)}
                  style={{
                    background: isSelected ? 'rgba(0, 212, 255, 0.15)' : 'rgba(4, 10, 24, 0.6)',
                    border: isSelected ? '1px solid #00d4ff' : '1px solid rgba(255, 255, 255, 0.1)',
                    color: isSelected ? '#ffffff' : 'rgba(255, 255, 255, 0.7)',
                    borderRadius: 4,
                    padding: '8px 16px',
                    fontFamily: 'var(--font-mono)',
                    fontSize: 11,
                    fontWeight: 600,
                    letterSpacing: '0.08em',
                    cursor: 'pointer',
                    transition: 'all 0.2s ease',
                  }}
                >
                  {t.name}
                </button>
              );
            })}
          </div>

          {/* Active Quick Guide Details Container */}
          <div
            style={{
              background: 'rgba(3, 9, 22, 0.85)',
              border: '1px solid rgba(0, 212, 255, 0.25)',
              borderRadius: 8,
              padding: 'clamp(20px, 3vw, 36px)',
              backdropFilter: 'blur(12px)',
            }}
          >
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: 12, marginBottom: 24 }}>
              <div>
                <span style={{ fontFamily: 'var(--font-mono)', fontSize: 10, color: '#7cc4ff', letterSpacing: '0.14em' }}>
                  {activeGuide.code} // {activeGuide.badge}
                </span>
                <h3 style={{ fontFamily: 'var(--font-display)', fontSize: 22, fontWeight: 700, color: '#ffffff', margin: '4px 0 0 0' }}>
                  {activeGuide.name}
                </h3>
              </div>
              <button
                onClick={() => {
                  if (activeGuide.id === 'demo') {
                    handleLaunchDemo();
                  } else {
                    setScreen(activeGuide.targetScreen);
                  }
                }}
                style={{
                  background: '#00d4ff',
                  color: '#020409',
                  border: 'none',
                  borderRadius: 4,
                  padding: '8px 18px',
                  fontFamily: 'var(--font-mono)',
                  fontSize: 10,
                  fontWeight: 700,
                  letterSpacing: '0.12em',
                  cursor: 'pointer',
                }}
              >
                OPEN {activeGuide.name.toUpperCase()} →
              </button>
            </div>

            {/* 3 Structured Columns: WHAT IT DOES, HOW TO USE IT, WHAT YOU CAN LEARN */}
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))', gap: 20 }}>
              {/* WHAT IT DOES */}
              <div
                style={{
                  background: 'rgba(0,0,0,0.35)',
                  border: '1px solid rgba(0, 212, 255, 0.15)',
                  borderRadius: 6,
                  padding: '20px 18px',
                }}
              >
                <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 10 }}>
                  <span style={{ width: 6, height: 6, borderRadius: '50%', background: '#00d4ff' }} />
                  <span style={{ fontFamily: 'var(--font-mono)', fontSize: 11, fontWeight: 700, color: '#00d4ff', letterSpacing: '0.1em' }}>
                    WHAT IT DOES
                  </span>
                </div>
                <p style={{ fontFamily: 'var(--font-body)', fontSize: 13, color: 'rgba(255,255,255,0.8)', lineHeight: 1.6, margin: 0 }}>
                  {activeGuide.whatItDoes}
                </p>
              </div>

              {/* HOW TO USE IT */}
              <div
                style={{
                  background: 'rgba(0,0,0,0.35)',
                  border: '1px solid rgba(124, 196, 255, 0.15)',
                  borderRadius: 6,
                  padding: '20px 18px',
                }}
              >
                <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 10 }}>
                  <span style={{ width: 6, height: 6, borderRadius: '50%', background: '#7cc4ff' }} />
                  <span style={{ fontFamily: 'var(--font-mono)', fontSize: 11, fontWeight: 700, color: '#7cc4ff', letterSpacing: '0.1em' }}>
                    HOW TO USE IT
                  </span>
                </div>
                <p style={{ fontFamily: 'var(--font-body)', fontSize: 13, color: 'rgba(255,255,255,0.8)', lineHeight: 1.6, margin: 0 }}>
                  {activeGuide.howToUseIt}
                </p>
              </div>

              {/* WHAT YOU CAN LEARN */}
              <div
                style={{
                  background: 'rgba(0,0,0,0.35)',
                  border: '1px solid rgba(0, 255, 136, 0.15)',
                  borderRadius: 6,
                  padding: '20px 18px',
                }}
              >
                <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 10 }}>
                  <span style={{ width: 6, height: 6, borderRadius: '50%', background: '#00ff88' }} />
                  <span style={{ fontFamily: 'var(--font-mono)', fontSize: 11, fontWeight: 700, color: '#00ff88', letterSpacing: '0.1em' }}>
                    WHAT YOU CAN LEARN
                  </span>
                </div>
                <p style={{ fontFamily: 'var(--font-body)', fontSize: 13, color: 'rgba(255,255,255,0.8)', lineHeight: 1.6, margin: 0 }}>
                  {activeGuide.whatYouCanLearn}
                </p>
              </div>
            </div>
          </div>
        </section>

        {/* ══════════════════════════════════════════════════════════════
            SECTION 6 — READY TO EXPLORE?
            ══════════════════════════════════════════════════════════════ */}
        <section
          id="sec-ready-to-explore"
          style={{
            paddingTop: 'clamp(56px, 10vh, 96px)',
            paddingBottom: 'clamp(64px, 12vh, 110px)',
            textAlign: 'center',
            position: 'relative',
          }}
        >
          <div
            style={{
              background: 'linear-gradient(180deg, rgba(3, 10, 24, 0.8) 0%, rgba(2, 6, 16, 0.95) 100%)',
              border: '1px solid rgba(0, 212, 255, 0.3)',
              borderRadius: 12,
              padding: 'clamp(36px, 6vw, 64px) clamp(20px, 4vw, 48px)',
              position: 'relative',
              overflow: 'hidden',
              boxShadow: '0 0 50px rgba(0, 212, 255, 0.12)',
            }}
          >
            {/* Subtle glow ring behind title */}
            <div
              style={{
                position: 'absolute',
                top: '50%',
                left: '50%',
                transform: 'translate(-50%, -50%)',
                width: '600px',
                height: '300px',
                background: 'radial-gradient(ellipse at center, rgba(0, 212, 255, 0.1) 0%, transparent 70%)',
                pointerEvents: 'none',
              }}
            />

            <div
              style={{
                fontFamily: 'var(--font-mono, monospace)',
                fontSize: 11,
                color: '#00d4ff',
                letterSpacing: '0.2em',
                textTransform: 'uppercase',
                marginBottom: 16,
                fontWeight: 600,
              }}
            >
              MISSION CONTROL AWAITING FLIGHT INITIATION
            </div>

            <h2
              style={{
                fontFamily: 'var(--font-editorial, "Syne", sans-serif)',
                fontSize: 'clamp(32px, 4.5vw, 54px)',
                fontWeight: 800,
                letterSpacing: '0.04em',
                color: '#ffffff',
                margin: '0 0 16px 0',
                lineHeight: 1.15,
              }}
            >
              READY TO BEGIN YOUR JOURNEY?
            </h2>

            <p
              style={{
                fontFamily: 'var(--font-serif, "Cormorant Garamond", Georgia, serif)',
                fontSize: 'clamp(18px, 2vw, 24px)',
                fontStyle: 'italic',
                color: '#7cc4ff',
                maxWidth: 720,
                margin: '0 auto 36px auto',
                lineHeight: 1.45,
              }}
            >
              "Explore space missions, create your own and discover how VYOM makes space easier to understand."
            </p>

            {/* Two Action Buttons */}
            <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', gap: 18, flexWrap: 'wrap' }}>
              <button
                onClick={handleLaunchDemo}
                style={{
                  background: 'linear-gradient(135deg, #00d4ff 0%, #0088cc 100%)',
                  color: '#020409',
                  border: 'none',
                  borderRadius: 4,
                  padding: '16px 34px',
                  fontFamily: 'var(--font-mono, monospace)',
                  fontSize: 12,
                  fontWeight: 800,
                  letterSpacing: '0.14em',
                  cursor: 'pointer',
                  boxShadow: '0 0 24px rgba(0, 212, 255, 0.4)',
                  transition: 'all 0.25s ease',
                }}
              >
                TRY DEMO MISSION
              </button>

              <button
                onClick={() => setScreen('onboarding')}
                style={{
                  background: 'rgba(255, 255, 255, 0.05)',
                  color: '#ffffff',
                  border: '1px solid rgba(255, 255, 255, 0.25)',
                  borderRadius: 4,
                  padding: '16px 34px',
                  fontFamily: 'var(--font-mono, monospace)',
                  fontSize: 12,
                  fontWeight: 700,
                  letterSpacing: '0.14em',
                  cursor: 'pointer',
                  transition: 'all 0.25s ease',
                }}
              >
                CREATE YOUR MISSION
              </button>
            </div>
          </div>
        </section>

      </main>

      {/* ── FOOTER ────────────────────────────────────────────────── */}
      <footer
        style={{
          borderTop: '1px solid rgba(255, 255, 255, 0.08)',
          background: '#010307',
          padding: '28px clamp(16px, 4vw, 48px)',
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          flexWrap: 'wrap',
          gap: 16,
          boxSizing: 'border-box',
          position: 'relative',
          zIndex: 1,
        }}
      >
        <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
          <span style={{ fontFamily: 'var(--font-display)', fontSize: 13, fontWeight: 700, color: '#fff', letterSpacing: '0.12em' }}>
            VYOM
          </span>
          <span style={{ color: 'rgba(255,255,255,0.2)' }}>|</span>
          <span style={{ fontFamily: 'var(--font-mono)', fontSize: 10, color: 'rgba(255,255,255,0.45)', letterSpacing: '0.08em' }}>
            SPACE MISSION DIGITAL TWIN
          </span>
        </div>
        <div style={{ fontFamily: 'var(--font-mono)', fontSize: 10, color: 'rgba(255,255,255,0.4)' }}>
          ALL TELEMETRY, ORBITS & MODELS ARE SIMULATED FOR EDUCATIONAL EXPLORATION
        </div>
      </footer>
    </div>
  );
}
