/**
 * VYOM — Gamified Learning Mode Educational Content & Database
 * Beginner-friendly, engaging aerospace engineering concepts designed for students and researchers.
 */

import type {
  GamifiedMission,
  SatelliteComponentItem,
  OrbitDefinition,
  SpaceChallenge,
  LaunchStageInfo,
} from '../types/gamified';

export const GAMIFIED_MISSIONS: GamifiedMission[] = [
  {
    id: 'flood-monitoring',
    title: 'Flood Hazard Monitoring',
    tagline: 'Track floodwaters & rescue routes through storm clouds',
    category: 'DISASTER MANAGEMENT',
    difficulty: 'Beginner',
    icon: '🌊',
    badge: 'RAPID RESPONSE',
    accentColor: '#00d4ff',
    objective: 'Provide real-time flood inundation maps to emergency disaster rescue teams on the ground.',
    satelliteTask: 'Penetrate heavy monsoon cloud cover and accurately map flooded river basins, submerged roads, and isolated towns.',
    recommendedPayload: 'Radar (Synthetic Aperture Radar / SAR)',
    recommendedOrbit: 'LEO',
    whyOrbit: 'Low Earth Orbit (400-600 km) passes close to Earth, providing the crisp high-resolution images needed to see flooded streets and bridges.',
    whyPayload: 'Optical cameras cannot see through dense storm clouds or rain. Radar actively sends microwave pulses that pierce straight through clouds and darkness to map standing water.',
    aiIntro: 'Floods happen during intense cloudbursts and monsoons when optical cameras are blinded by clouds. Your satellite needs special sensors that can see through storms and an orbit that gives close-up detail!',
  },
  {
    id: 'weather-monitoring',
    title: 'Global Weather & Storms',
    tagline: 'Watch cyclones, hurricanes & jet streams evolve 24/7',
    category: 'METEOROLOGY',
    difficulty: 'Intermediate',
    icon: '🌀',
    badge: 'PLANETARY RADAR',
    accentColor: '#9b5de5',
    objective: 'Monitor tropical storm formation, atmospheric moisture fronts, and cloud dynamics across an entire hemisphere.',
    satelliteTask: 'Keep an uninterrupted 24/7 watch over oceans and continents without moving away or losing sight of developing cyclones.',
    recommendedPayload: 'Thermal Sensor (Infrared Sounder)',
    recommendedOrbit: 'GEO',
    whyOrbit: 'Geostationary Orbit (35,786 km) matches Earth’s rotation speed exactly. The satellite appears stationary over one region, watching developing cyclones 24/7 without interruption.',
    whyPayload: 'Thermal infrared sensors measure the temperature of cloud tops: tall, dangerous thunderstorm towers are freezing cold at the top, allowing meteorologists to calculate storm intensity.',
    aiIntro: 'To predict where a cyclone will make landfall, meteorologists cannot afford to wait hours between photos. We need an orbit that stares continuously at the same hemisphere!',
  },
  {
    id: 'communication',
    title: 'Global Communications Relay',
    tagline: 'Connect remote schools, islands & disaster zones',
    category: 'TELECOMMUNICATIONS',
    difficulty: 'Beginner',
    icon: '📡',
    badge: 'CONNECTIVITY',
    accentColor: '#00ff88',
    objective: 'Provide high-speed broadband internet, emergency voice relays, and TV broadcasts to remote areas.',
    satelliteTask: 'Transmit high-bandwidth radio signals continuously to ground dishes across large landmasses.',
    recommendedPayload: 'High-Gain Antenna',
    recommendedOrbit: 'GEO',
    whyOrbit: 'A GEO orbit lets ground dishes point permanently at one spot in the sky without motorized tracking systems, creating reliable 24/7 broadband relays.',
    whyPayload: 'High-gain parabolic antennas focus radio waves into tight, powerful spot beams, ensuring clear signals even across 36,000 kilometers of space.',
    aiIntro: 'Space communication connects billions of people. Your satellite acts like a giant celestial radio tower floating high above Earth. Let’s design a powerful communications relay!',
  },
  {
    id: 'forest-fire',
    title: 'Forest Fire Early Warning',
    tagline: 'Spot thermal anomalies before fires spread out of control',
    category: 'ENVIRONMENTAL DEFENSE',
    difficulty: 'Intermediate',
    icon: '🔥',
    badge: 'THERMAL SHIELD',
    accentColor: '#ff8c00',
    objective: 'Detect newly ignited wildfires and track fire spread vectors through thick smoke blankets.',
    satelliteTask: 'Identify small thermal anomalies and transmit precise GPS coordinates of fire lines to forest ranger command centers.',
    recommendedPayload: 'Thermal Sensor',
    recommendedOrbit: 'LEO',
    whyOrbit: 'LEO orbits are close enough to detect small, early-stage fire spots (as small as 10 meters across) before they explode into uncontrollable infernos.',
    whyPayload: 'Flames and smoldering embers emit strong mid-wave and long-wave infrared radiation that passes right through thick smoke, revealing the active fire perimeter.',
    aiIntro: 'Early detection is the golden hour of firefighting. If your satellite can detect a spark before it becomes a wildfire, thousands of acres of forest and wildlife are saved!',
  },
  {
    id: 'earth-mapping',
    title: 'Ultra-High Resolution Cartography',
    tagline: 'Map cities, topography & agricultural crop health',
    category: 'SURFACE CARTOGRAPHY',
    difficulty: 'Advanced',
    icon: '🗺️',
    badge: 'SUB-METER SURVEY',
    accentColor: '#38bdf8',
    objective: 'Build 3D digital elevation models, track urban infrastructure expansion, and analyze farm irrigation.',
    satelliteTask: 'Capture sharp, multispectral optical photography with consistent solar illumination across consecutive orbits.',
    recommendedPayload: 'Optical Camera',
    recommendedOrbit: 'LEO',
    whyOrbit: 'A Sun-Synchronous LEO orbit ensures the satellite passes over each city at the exact same local solar time every day, keeping shadow lengths consistent for accurate 3D mapping.',
    whyPayload: 'A large aperture optical telescope captures crisp sub-meter resolution in red, green, blue, and near-infrared light to analyze chlorophyll health in crops.',
    aiIntro: 'High-precision cartography powers everything from modern smartphone maps to precision farming. You need extreme optical clarity and perfect solar lighting consistency!',
  },
];

// ── Satellite Components ──────────────────────────────────────────────────────

export const SATELLITE_COMPONENTS: Record<string, SatelliteComponentItem> = {
  // Payloads
  'optical-camera': {
    id: 'optical-camera',
    category: 'payload',
    name: 'High-Resolution Optical Camera',
    icon: '📷',
    subtitle: 'Multispectral Visual & Near-IR Telescope',
    weightKg: 60,
    powerUsageW: 25,
    fuelUsageKg: 0,
    purpose: 'Captures vivid, color photographs of Earth’s surface with sub-meter detail.',
    howItWorks: 'Uses folded Cassegrain telescope mirrors and a high-sensitivity CMOS sensor array to collect visible light reflected from Earth.',
    suitableMissions: ['earth-mapping'],
    suitabilityExplanations: {
      'flood-monitoring': 'Suboptimal: Optical cameras cannot see through dense rain clouds or storm systems during a flood emergency.',
      'weather-monitoring': 'Acceptable for daytime cloud viewing, but fails at night and cannot measure cloud temperature directly.',
      'communication': 'Unsuitable: A communication satellite requires RF antennas rather than an imaging camera.',
      'forest-fire': 'Suboptimal: Visible light is blinded by thick white smoke from forest fires.',
      'earth-mapping': 'Optimal! High-resolution optical mirrors provide crystal-clear ground imagery and color multispectral bands.',
    },
  },
  'thermal-sensor': {
    id: 'thermal-sensor',
    category: 'payload',
    name: 'Infrared Thermal Sensor',
    icon: '🌡️',
    subtitle: 'Cryo-Cooled Mid/Long-Wave IR Radiometer',
    weightKg: 50,
    powerUsageW: 30,
    fuelUsageKg: 0,
    purpose: 'Measures heat and temperature signatures emitted by Earth’s surface, clouds, and fires.',
    howItWorks: 'Uses germanium lenses and a cryogenic Stirling cooler to detect electromagnetic radiation between 3.5 and 12 micrometers wavelength.',
    suitableMissions: ['forest-fire', 'weather-monitoring'],
    suitabilityExplanations: {
      'flood-monitoring': 'Suboptimal: While it can see differences in water temperature, it lacks the sharp edge resolution of radar for flood boundaries.',
      'weather-monitoring': 'Optimal! Measures cloud-top temperatures 24/7 to determine storm height and cyclone intensity.',
      'communication': 'Unsuitable: Does not transmit communications or radio frequencies.',
      'forest-fire': 'Optimal! Detects intense heat radiation through thick smoke and pinpoints hotspots even at night.',
      'earth-mapping': 'Suboptimal: Provides low geometric resolution compared to an optical camera.',
    },
  },
  'radar': {
    id: 'radar',
    category: 'payload',
    name: 'Synthetic Aperture Radar (SAR)',
    icon: '📡',
    subtitle: 'All-Weather Active Microwave Radar Panel',
    weightKg: 95,
    powerUsageW: 75,
    fuelUsageKg: 0,
    purpose: 'Bounces active microwave pulses off the ground to map terrain through clouds, rain, and complete darkness.',
    howItWorks: 'Transmits microwave chirp signals and records the reflected echo timing and phase shifts to build photographic-quality radar maps.',
    suitableMissions: ['flood-monitoring', 'earth-mapping'],
    suitabilityExplanations: {
      'flood-monitoring': 'Optimal! Smooth water surfaces reflect radar beams away, making flooded areas appear pitch black against rough land — 100% cloudproof!',
      'weather-monitoring': 'Suboptimal: Too heavy and narrow-swath for observing hemisphere-wide atmospheric storm patterns.',
      'communication': 'Unsuitable: Designed for ground radar imaging, not telecom relays.',
      'forest-fire': 'Acceptable for mapping burned topography, but cannot detect fire temperatures directly like a thermal sensor.',
      'earth-mapping': 'Good for 3D elevation topography, but uses higher power and does not produce color images.',
    },
  },

  // Power
  'standard-solar': {
    id: 'standard-solar',
    category: 'power',
    name: 'Standard Solar Panels',
    icon: '☀️',
    subtitle: 'Fixed Silicon Photovoltaic Wings',
    weightKg: 35,
    powerUsageW: -90, // Generates 90W
    fuelUsageKg: 0,
    purpose: 'Converts sunlight into electricity to run your satellite instruments and charge onboard batteries.',
    howItWorks: 'Single-junction silicon solar cells absorb photons and release electrons through the photovoltaic effect.',
    suitableMissions: ['flood-monitoring', 'earth-mapping', 'forest-fire', 'weather-monitoring', 'communication'],
    suitabilityExplanations: {
      'flood-monitoring': 'Acceptable, but check your total power if using radar, which consumes heavy wattage.',
      'weather-monitoring': 'Acceptable for basic sensors, but advanced payloads in GEO benefit from higher power margins.',
      'communication': 'Suboptimal: High-gain communications transmitters require high continuous power.',
      'forest-fire': 'Optimal: Provides ample electricity for thermal radiometers without adding excess weight.',
      'earth-mapping': 'Optimal: Lightweight and provides clean power for optical cameras.',
    },
  },
  'advanced-solar': {
    id: 'advanced-solar',
    category: 'power',
    name: 'Advanced Articulated Solar Arrays',
    icon: '⚡',
    subtitle: 'Dual Sun-Tracking Multi-Junction GaAs Wings',
    weightKg: 65,
    powerUsageW: -190, // Generates 190W
    fuelUsageKg: 0,
    purpose: 'High-output solar arrays that rotate automatically to face the sun for maximum continuous energy.',
    howItWorks: 'Triple-junction Gallium Arsenide (GaAs) solar cells with motorized Drive Units (SADA) achieve over 30% solar conversion efficiency.',
    suitableMissions: ['flood-monitoring', 'weather-monitoring', 'communication', 'forest-fire', 'earth-mapping'],
    suitabilityExplanations: {
      'flood-monitoring': 'Optimal! Provides generous surplus power required for radar transmitters and frequent data uplinks.',
      'weather-monitoring': 'Optimal! Guarantees 24/7 power stability for long-range GEO operations.',
      'communication': 'Optimal! Supplies the massive power needed for multi-channel RF amplifiers and traveling-wave tube transmitters.',
      'forest-fire': 'Great energy margin, though slightly heavier than standard panels.',
      'earth-mapping': 'Provides plenty of power for high-speed image downlink transmitters.',
    },
  },

  // Communication
  'basic-antenna': {
    id: 'basic-antenna',
    category: 'communication',
    name: 'Omnidirectional Whip Antenna',
    icon: '📻',
    subtitle: 'Low-Frequency S-Band Telemetry & Telecommand',
    weightKg: 15,
    powerUsageW: 15,
    fuelUsageKg: 0,
    purpose: 'Sends essential health data (temperature, battery) and receives simple commands from mission control.',
    howItWorks: 'Broadcasts radio waves in all directions like a radio station, meaning it never needs to be pointed accurately.',
    suitableMissions: ['flood-monitoring', 'forest-fire', 'earth-mapping'],
    suitabilityExplanations: {
      'flood-monitoring': 'Suboptimal: Flooding images have very large file sizes and take too long to download over a slow basic antenna.',
      'weather-monitoring': 'Suboptimal: Cannot transmit heavy meteorological video feeds back to Earth.',
      'communication': 'Unsuitable: A communication satellite must relay high-speed internet and media, which requires a high-gain antenna.',
      'forest-fire': 'Acceptable for sending rapid fire-warning alerts and GPS coordinates.',
      'earth-mapping': 'Suboptimal: Gigabytes of high-res optical imagery will suffer severe downlink bottlenecks.',
    },
  },
  'high-gain-antenna': {
    id: 'high-gain-antenna',
    category: 'communication',
    name: 'High-Gain Parabolic Dish',
    icon: '🛰️',
    subtitle: 'Steerable X/Ka-Band Gigabit Downlink Dish',
    weightKg: 45,
    powerUsageW: 35,
    fuelUsageKg: 0,
    purpose: 'Beams massive amounts of data, high-resolution imagery, and broadband telecom down to ground stations.',
    howItWorks: 'A curved parabolic dish focuses microwave radio beams into a laser-tight directional beam, increasing signal strength a thousand-fold.',
    suitableMissions: ['flood-monitoring', 'weather-monitoring', 'communication', 'forest-fire', 'earth-mapping'],
    suitabilityExplanations: {
      'flood-monitoring': 'Optimal! Downlinks large radar images in seconds so emergency rescue teams get instant maps.',
      'weather-monitoring': 'Optimal! Provides high-bandwidth streaming of atmospheric imaging channels.',
      'communication': 'Optimal! Essential for high-speed voice, internet, and broadcast communications.',
      'forest-fire': 'Optimal! Transmits multi-spectral infrared burn maps to ground command without delay.',
      'earth-mapping': 'Optimal! Downloads thousands of high-definition surface maps per day.',
    },
  },

  // Control
  'basic-control': {
    id: 'basic-control',
    category: 'control',
    name: 'Basic 3-Axis Reaction Wheels',
    icon: '🧭',
    subtitle: 'Flywheels & Magnetic Torquer Attitude Control',
    weightKg: 25,
    powerUsageW: 15,
    fuelUsageKg: 10,
    purpose: 'Keeps the satellite pointing in the right direction using spinning electric flywheels.',
    howItWorks: 'Spins internal heavy wheels to apply Newton’s third law (action and reaction) to turn the spacecraft smoothly without burning fuel.',
    suitableMissions: ['weather-monitoring', 'communication', 'forest-fire'],
    suitabilityExplanations: {
      'flood-monitoring': 'Acceptable for steady pointing, though radar payloads benefit from fast slewing maneuvers.',
      'weather-monitoring': 'Optimal! Smooth, vibration-free pointing ideal for long-duration staring from GEO.',
      'communication': 'Optimal! Very reliable for holding a constant orientation towards Earth.',
      'forest-fire': 'Good, provides reliable nadir pointing over forest zones.',
      'earth-mapping': 'Acceptable, but advanced control allows faster target-to-target slewing.',
    },
  },
  'advanced-control': {
    id: 'advanced-control',
    category: 'control',
    name: 'Advanced RCS Thruster & Star Tracker System',
    icon: '🎯',
    subtitle: 'Precision Gyros, Star Trackers & Monopropellant RCS',
    weightKg: 50,
    powerUsageW: 30,
    fuelUsageKg: 30,
    purpose: 'Provides pinpoint accuracy (down to fractions of a degree) and rapid orbit maneuverability.',
    howItWorks: 'Star camera sensors match constellations in deep space to calculate attitude, while hydrazine chemical thrusters execute sharp orientation changes.',
    suitableMissions: ['earth-mapping', 'flood-monitoring', 'forest-fire', 'weather-monitoring', 'communication'],
    suitabilityExplanations: {
      'flood-monitoring': 'Optimal! Rapid slewing allows emergency retargeting to point directly at sudden disaster areas.',
      'weather-monitoring': 'Provides precision station-keeping against gravitational perturbations in GEO.',
      'communication': 'Excellent for maintaining pinpoint radio beam alignment with ground station antennas.',
      'forest-fire': 'Optimal! Star trackers ensure GPS-grade geographic geolocation of forest fire perimeters.',
      'earth-mapping': 'Optimal! Sub-meter cartography requires ultra-precise stability to avoid motion blur.',
    },
  },
};

// ── Orbits ───────────────────────────────────────────────────────────────────

export const ORBIT_DEFINITIONS: Record<string, OrbitDefinition> = {
  LEO: {
    type: 'LEO',
    name: 'Low Earth Orbit (LEO)',
    altitudeKm: '400 – 700 km',
    orbitalPeriod: '90 – 100 minutes',
    coverageDescription: 'Close to Earth, circles the globe 15 times a day. Covers narrow swaths with immense detail.',
    pros: [
      'Highest spatial resolution (see cars, houses, flooded streets)',
      'Lowest launch energy and rocket weight required',
      'Low communication latency (< 30 milliseconds)',
    ],
    cons: [
      'Fast-moving: passes overhead in only 10–15 minutes',
      'Atmospheric drag slowly decays the orbit over time',
      'Requires multiple satellites for continuous planetary coverage',
    ],
    bestFor: 'Earth observation, flood detection, wildfire surveillance, sub-meter mapping, and scientific experiments.',
    groundResolution: 'Ultra-High (< 1m)',
    recommendedForMissions: ['flood-monitoring', 'forest-fire', 'earth-mapping'],
  },
  MEO: {
    type: 'MEO',
    name: 'Medium Earth Orbit (MEO)',
    altitudeKm: '10,000 – 20,000 km',
    orbitalPeriod: '6 – 12 hours',
    coverageDescription: 'Balanced altitude between LEO and GEO. Sweeps over vast continents in steady multi-hour passes.',
    pros: [
      'Wider coverage footprint than LEO without GEO launch costs',
      'Each satellite is visible for several hours from one ground point',
      'Ideal balance between latency and coverage footprint',
    ],
    cons: [
      'Passes through the intense Van Allen Radiation Belts',
      'Lower resolution than LEO for detailed photographic mapping',
      'Requires radiation-hardened electronics',
    ],
    bestFor: 'Global navigation constellations (GPS, NavIC, Galileo) and regional high-throughput broadband relays.',
    groundResolution: 'Medium (10-50m)',
    recommendedForMissions: ['communication'],
  },
  GEO: {
    type: 'GEO',
    name: 'Geostationary Orbit (GEO)',
    altitudeKm: '35,786 km',
    orbitalPeriod: '24 hours (Matches Earth rotation)',
    coverageDescription: 'High above the equator. Orbit period matches Earth’s rotation, so the satellite stays stationary over one region forever.',
    pros: [
      'Uninterrupted 24/7 continuous coverage of 1/3 of Earth',
      'Ground dishes never need motorized tracking',
      'Perfect for weather tracking and television broadcasts',
    ],
    cons: [
      'High launch energy: requires massive rocket boosters',
      'Far distance creates noticeable radio latency (~250 ms delay)',
      'Cannot view polar regions (Arctic and Antarctica)',
    ],
    bestFor: 'Continuous hemispheric weather surveillance, telecommunications, TV broadcast, and missile early warning.',
    groundResolution: 'Broad Regional (500m+)',
    recommendedForMissions: ['weather-monitoring', 'communication'],
  },
};

// ── 7 Launch Stages ──────────────────────────────────────────────────────────

export const LAUNCH_STAGES: LaunchStageInfo[] = [
  {
    index: 1,
    name: 'COUNTDOWN & IGNITION',
    label: 'T-Minus 5 Seconds',
    description: 'Launch pad cryogenic venting stops. Fuel valves open and the core rocket engine ignites with roaring thrust.',
    altitudeKm: 0,
    velocityKms: 0,
    telemetryMsg: 'IGNITION SEQUENCE START. CORE ENGINES NOMINAL AT 102% RATED THRUST.',
  },
  {
    index: 2,
    name: 'LIFTOFF & TOWER CLEARANCE',
    label: 'T+ 00:15 Liftoff',
    description: 'The launch clamps release! The rocket ascends vertically through the dense lower atmosphere on a column of fire.',
    altitudeKm: 2.5,
    velocityKms: 0.35,
    telemetryMsg: 'LIFTOFF! VYOM CARRIER VEHICLE HAS CLEARED THE LAUNCH UMBILICAL TOWER.',
  },
  {
    index: 3,
    name: 'EARTH DEPARTURE & STAGING',
    label: 'T+ 02:40 Booster Separation',
    description: 'Having pushed the rocket through maximum aerodynamic pressure (Max-Q), the spent first stage separates and drops away.',
    altitudeKm: 85,
    velocityKms: 2.4,
    telemetryMsg: 'MAIN ENGINE CUTOFF (MECO). FIRST STAGE SEPARATION CONFIRMED.',
  },
  {
    index: 4,
    name: 'FAIRING JETTISON',
    label: 'T+ 03:30 Fairing Release',
    description: 'Above the dense atmosphere, the aerodynamic clamshell fairings open and discard, exposing the satellite to the vacuum of space.',
    altitudeKm: 140,
    velocityKms: 4.8,
    telemetryMsg: 'PAYLOAD FAIRINGS JETTISONED. SATELLITE EXPOSED TO FREE SPACE VACUUM.',
  },
  {
    index: 5,
    name: 'SATELLITE SEPARATION',
    label: 'T+ 08:20 Orbit Insertion',
    description: 'The upper stage engine shuts down at target orbital velocity. Mechanical latches release your satellite into independent orbit.',
    altitudeKm: 520,
    velocityKms: 7.6,
    telemetryMsg: 'SATELLITE SEPARATION CONFIRMED! SPACECRAFT IS IN FREE ORBITAL FLIGHT.',
  },
  {
    index: 6,
    name: 'SOLAR PANEL DEPLOYMENT',
    label: 'T+ 12:00 Power Generation',
    description: 'Folded solar panel arrays unlatch, rotate outward, and lock in place. Solar cells face the sun to generate clean electricity.',
    altitudeKm: 520,
    velocityKms: 7.6,
    telemetryMsg: 'SOLAR ARRAYS FULLY UNFURLED. BATTERY CHARGING TELEMETRY LOCKED.',
  },
  {
    index: 7,
    name: 'MISSION START & LOCK-IN',
    label: 'T+ 15:00 Operations Live',
    description: 'Attitude control wheels stabilize rotation. Communication link established with Mission Control ground stations.',
    altitudeKm: 520,
    velocityKms: 7.6,
    telemetryMsg: 'ALL SYSTEMS NOMINAL. VYOM MISSION DIGITAL TWIN IS OFFICIALLY OPERATIONAL!',
  },
];

// ── In-Mission Space Challenges ──────────────────────────────────────────────

export const SPACE_CHALLENGES: SpaceChallenge[] = [
  {
    id: 'solar-panel-damage',
    title: 'Micro-Meteorite Solar Array Impact',
    system: 'power',
    visualEffect: 'solar-sparks',
    description: 'A tiny hypervelocity space dust speck has struck the port solar array! Sparks have created a short circuit, reducing total power generation by 35%.',
    urgency: 'High',
    options: [
      {
        id: 'isolate-and-angle',
        label: 'Isolate Damaged String & Optimize Sun-Angle',
        description: 'Command the onboard Power Distribution Unit to isolate the shorted circuit, then tilt the remaining healthy panels directly into the peak sun line.',
        isRecommended: true,
        healthDelta: 5,
        powerDelta: 20,
        commsDelta: 0,
        feedback: 'Brilliant engineering! By isolating the damaged cell string, you prevented battery drainage. Re-angling the remaining cells restored power to 90%!',
        realWorldAnalogy: 'In real space missions like the Hubble Space Telescope, engineers frequently isolate damaged solar strings without losing the whole spacecraft.',
      },
      {
        id: 'ignore-and-continue',
        label: 'Ignore Warning and Keep Running All Instruments',
        description: 'Take no action and hope the onboard batteries can cover the electrical deficit.',
        isRecommended: false,
        healthDelta: -25,
        powerDelta: -40,
        commsDelta: -10,
        feedback: 'Dangerous choice! Running full payload on a damaged power array drained your reserve batteries down to critical brownout levels.',
        realWorldAnalogy: 'Ignoring electrical shorts in space can lead to complete battery swelling and permanent mission termination.',
      },
      {
        id: 'emergency-safe-mode',
        label: 'Enter Safe Mode and Power Down Scientific Payload',
        description: 'Immediately power off the imaging payload and enter low-power sun-pointing safe mode while running diagnostics.',
        isRecommended: true,
        healthDelta: 10,
        powerDelta: 10,
        commsDelta: -5,
        feedback: 'Cautious and safe. You preserved battery health, though scientific data collection was temporarily paused while engineers reviewed telemetry.',
        realWorldAnalogy: 'ISRO and NASA satellites automatically trigger Safe Mode whenever unexpected power dips occur.',
      },
    ],
  },
  {
    id: 'communication-failure',
    title: 'Ground Station Signal Loss',
    system: 'communication',
    visualEffect: 'signal-loss',
    description: 'Ground telemetry indicates a sudden carrier frequency fade. Radio signal strength dropped from -85 dBm to -125 dBm as the satellite passed over the ground station.',
    urgency: 'Medium',
    options: [
      {
        id: 'reorient-dish',
        label: 'Recalibrate Antenna Gimbal & Switch to Backup Beacon',
        description: 'Send an automated ping to re-center the steerable dish on the ground station azimuth and broadcast a low-frequency telemetry beacon.',
        isRecommended: true,
        healthDelta: 5,
        powerDelta: -5,
        commsDelta: 35,
        feedback: 'Link restored! The low-rate beacon acquired ground lock and automatically drove the dish back to exact boresight alignment.',
        realWorldAnalogy: 'Deep space probes like Voyager and Mars Orbiter use omnidirectional backup beacons whenever the main high-gain dish loses earth-lock.',
      },
      {
        id: 'boost-transmitter-power',
        label: 'Crank Radio Transmitter to Maximum Wattage',
        description: 'Overdrive the RF amplifier to blast through the signal loss without checking dish pointing.',
        isRecommended: false,
        healthDelta: -15,
        powerDelta: -30,
        commsDelta: 5,
        feedback: 'Wasteful power consumption! Cranking transmitter power while the antenna was pointing in the wrong direction burned battery power with minimal gain.',
        realWorldAnalogy: 'RF amplifiers generate intense heat in vacuum. Blasting max power off-target risks overheating communication transponders.',
      },
      {
        id: 'buffer-on-recorder',
        label: 'Buffer Data to Solid-State Recorder & Wait for Next Pass',
        description: 'Store all mission observations onboard the solid-state memory drive and wait for the next ground station contact window.',
        isRecommended: true,
        healthDelta: 5,
        powerDelta: 5,
        commsDelta: 15,
        feedback: 'Smart operational patience! No scientific data was lost because your onboard solid-state recorder buffered all telemetry until the next ground station.',
        realWorldAnalogy: 'Earth observation satellites routinely record imagery over Antarctica and downlink it when flying over European or Indian ground stations.',
      },
    ],
  },
  {
    id: 'low-power',
    title: 'Orbital Eclipse Battery Depletion',
    system: 'power',
    visualEffect: 'battery-drain',
    description: 'The satellite has entered Earth’s shadow (eclipse). With zero solar power for 35 minutes, high instrument power draw is draining the lithium-ion batteries rapidly.',
    urgency: 'High',
    options: [
      {
        id: 'load-shedding',
        label: 'Execute Intelligent Load Shedding',
        description: 'Temporarily switch off non-critical heaters and stand down the imaging payload, maintaining only core avionics and survival heaters.',
        isRecommended: true,
        healthDelta: 10,
        powerDelta: 25,
        commsDelta: 0,
        feedback: 'Textbook spaceflight management! Shedding heavy electrical loads protected battery depth-of-discharge until the satellite emerged into bright sunlight.',
        realWorldAnalogy: 'Space stations and satellites execute automated load-shedding every single time they enter eclipse behind Earth.',
      },
      {
        id: 'keep-payload-on',
        label: 'Keep Nighttime Observations Active at Full Power',
        description: 'Leave all cameras and radar systems humming at 100% capacity throughout the eclipse.',
        isRecommended: false,
        healthDelta: -30,
        powerDelta: -45,
        commsDelta: -15,
        feedback: 'Battery brownout! Voltage dropped below the critical 22V threshold, triggering emergency hardware shutdowns and stressing battery cells.',
        realWorldAnalogy: 'Deeply discharging spacecraft batteries permanently reduces their chemical lifespan and can kill a mission within weeks.',
      },
      {
        id: 'duty-cycle',
        label: 'Pulse Payloads at 25% Duty Cycle',
        description: 'Operate instruments in short, intermittent bursts rather than full continuous operation.',
        isRecommended: true,
        healthDelta: 5,
        powerDelta: 10,
        commsDelta: 5,
        feedback: 'Balanced compromise! You gathered key night-side data while preventing battery voltage from falling into the red zone.',
        realWorldAnalogy: 'Space telescopes often pulse their cryo-coolers during eclipse to maintain thermal equilibrium without exhausting batteries.',
      },
    ],
  },
  {
    id: 'orbit-deviation',
    title: 'Atmospheric Drag Orbital Decay',
    system: 'orbit',
    visualEffect: 'orbit-drift',
    description: 'Solar activity has expanded Earth’s upper atmosphere, increasing aerodynamic drag. The satellite’s altitude has dropped by 18 kilometers, drifting from its planned ground track.',
    urgency: 'Medium',
    options: [
      {
        id: 'prograde-burn',
        label: 'Fire Prograde RCS Thrusters for Orbit Raising',
        description: 'Command a timed 45-second prograde thruster burn at apogee to raise the perigee altitude back to nominal flight orbit.',
        isRecommended: true,
        healthDelta: 10,
        powerDelta: -5,
        commsDelta: 0,
        feedback: 'Orbital velocity restored! The Hohmann transfer burn lifted your satellite back to its designated 500 km operating altitude.',
        realWorldAnalogy: 'The International Space Station performs regular reboost thruster burns every few weeks to counteract atmospheric drag.',
      },
      {
        id: 'attitude-feathering',
        label: 'Feather Solar Arrays to Minimize Frontal Cross-Section',
        description: 'Turn solar arrays edge-on to the velocity vector to reduce atmospheric drag without burning fuel.',
        isRecommended: true,
        healthDelta: 5,
        powerDelta: -10,
        commsDelta: 0,
        feedback: 'Clever aerodynamic technique! Feathering the wings halved the drag coefficient, slowing altitude loss until solar weather calmed down.',
        realWorldAnalogy: 'Spacecraft in very low orbits orient their solar wings like airplane wings slicing through thin air during solar geomagnetic storms.',
      },
      {
        id: 'do-nothing-orbit',
        label: 'Do Nothing and Let Gravity Take Its Course',
        description: 'Ignore the altitude drop to conserve onboard fuel.',
        isRecommended: false,
        healthDelta: -25,
        powerDelta: 0,
        commsDelta: -10,
        feedback: 'Uncontrolled descent! Drag continued to multiply exponentially. Ground repeat cycles were ruined, and the satellite risks premature atmospheric reentry.',
        realWorldAnalogy: 'Satellites that do not perform station-keeping burns eventually tumble into the dense atmosphere and burn up like meteors.',
      },
    ],
  },
  {
    id: 'sensor-failure',
    title: 'Payload Sensor Optical Calibration Drift',
    system: 'payload',
    visualEffect: 'sensor-glitch',
    description: 'Cosmic radiation and thermal cycling have caused optical distortion on the main sensor lens, producing blurred telemetry images.',
    urgency: 'Medium',
    options: [
      {
        id: 'stellar-calibration',
        label: 'Execute Dark-Frame & Stellar Calibration Routine',
        description: 'Point the sensor at deep dark space to map dead pixels, then image a known standard star to recalibrate focus and color sensitivity.',
        isRecommended: true,
        healthDelta: 15,
        powerDelta: -5,
        commsDelta: 10,
        feedback: 'Crystal clarity restored! Dark-frame subtraction cleaned the thermal noise, and star calibration aligned optical focus perfectly.',
        realWorldAnalogy: 'Space telescopes like James Webb and Cartosat routinely point at isolated reference stars to calibrate focal planes.',
      },
      {
        id: 'thermal-bakeout',
        label: 'Trigger Decontamination Thermal Bake-Out',
        description: 'Activate internal heater coils around the optical tube to evaporate any outgassed volatile contaminants.',
        isRecommended: true,
        healthDelta: 10,
        powerDelta: -15,
        commsDelta: 5,
        feedback: 'Decontamination successful! Heating the optics evaporated micro-condensates on the glass, restoring 98% image contrast.',
        realWorldAnalogy: 'Spacecraft optics are intentionally baked out using thermal heaters to drive off residue outgassed by glues and composites in vacuum.',
      },
      {
        id: 'software-filter-only',
        label: 'Apply Heavy Ground Sharpening Without Recalibrating',
        description: 'Do not adjust the satellite hardware; try to clean the blurry photos using digital sharpening algorithms on the ground.',
        isRecommended: false,
        healthDelta: -10,
        powerDelta: 0,
        commsDelta: -5,
        feedback: 'Low scientific quality. Software sharpening amplifies noise and cannot restore optical photons that were lost due to sensor drift.',
        realWorldAnalogy: 'No software filter can replace true in-orbit optical calibration.',
      },
    ],
  },
];
